const AdditionCard = [
  {
    name: "Jinx",
    part: "-",
    cost: "",
    attack: "-",
    shield: "-",
    heal: "-",
    class: "curse",
    tag: "unplayable,ethereal",
    img: "xx",
    keyword: "-",
    id: 1001,
    cardEffect:
      "Unplayable. Ethereal. At the end of your turn, your furthest Axie takes 15 damage.",
  },
  {
    name: "Daze",
    part: "-",
    cost: "",
    attack: "-",
    shield: "-",
    heal: "-",
    class: "curse",
    tag: "unplayable",
    img: "xx",
    keyword: "-",
    id: 1002,
    cardEffect: "Unplayable",
  },
  {
    name: "Confused",
    part: "-",
    cost: "",
    attack: "-",
    shield: "-",
    heal: "-",
    class: "curse",
    tag: "unplayable,ethereal",
    img: "xx",
    keyword: "-",
    id: 1003,
    cardEffect: "Unplayable. Ethereal.",
  },
  {
    name: "Goo",
    part: "-",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: "-",
    class: "curse",
    tag: "banish",
    img: "xx",
    keyword: "-",
    id: 1004,
    cardEffect: "Banish.",
  },
  {
    name: "Void",
    part: "-",
    cost: "",
    attack: "-",
    shield: "-",
    heal: "-",
    class: "curse",
    tag: "unplayable,ethereal",
    img: "xx",
    keyword: "-",
    id: 1005,
    cardEffect:
      "Unplayable. Ethereal. When you draw 1 or more Void, lose 1 Energy.",
  },
  {
    name: "Burn",
    part: "-",
    cost: "",
    attack: "-",
    shield: "-",
    heal: "-",
    class: "curse",
    tag: "unplayable",
    img: "xx",
    keyword: "-",
    id: 1006,
    cardEffect:
      "Unplayable. Ethereal. At the end of your turn, all allies take 8 damage.",
  },
  {
    name: "Blackmail",
    part: "-",
    cost: 0,
    attack: "-",
    shield: "-",
    heal: "-",
    class: "curse",
    tag: "taunt,banish",
    img: "xx",
    keyword: "-",
    id: 1007,
    cardEffect:
      "Apply Taunt to your furthest Axie for 2 turns. If this is not used, put it onto the top of your draw pile. Banish.",
  },
  //tool
  {
    name: "Lumber Shield",
    part: "-",
    cost: 0,
    attack: "-",
    shield: 12,
    heal: "-",
    class: "tool",
    tag: "retain,banish",
    img: "oo",
    keyword: "-",
    id: 2001,
    cardEffect: "Retain. Target any ally. Banish. Shield for 12, 0 energy.",
  },
  {
    name: "Strawberry",
    part: "-",
    cost: 0,
    attack: "-",
    shield: "-",
    heal: 60,
    class: "tool",
    tag: "retain,banish",
    img: "oo",
    keyword: "-",
    id: 2002,
    cardEffect: "Retain. Target any ally. Banish. Heal for 60, 0 energy.",
  },
  {
    name: "Pure Water",
    part: "-",
    cost: 0,
    attack: "-",
    shield: "-",
    heal: 6,
    class: "tool",
    tag: "retain,banish",
    img: "oo",
    keyword: "-",
    id: 2003,
    cardEffect: "Retain. Target any ally. Banish. Heal for 6, 0 energy.",
  },
  {
    name: "Mandarine",
    part: "-",
    cost: 0,
    attack: "-",
    shield: "-",
    heal: 30,
    class: "tool",
    tag: "retain,banish",
    img: "oo",
    keyword: "-",
    id: 2004,
    cardEffect: "Retain. Target any ally. Banish. Heal for 30, 0 energy.",
  },
];
//pacu
