//30張 2022/04/17
//5 not in
//35 o
//0 x [Nimo t, Baby, Little Crab, Puff]
//35 all

// let Aquatic = [
//   {
//     name: "Anemone h",
//     part: "Horn",
//     cost: 1,
//     attack: 50,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Whenever this Axie draws Anemone restore 20 HP.",
//     class: "Aquatic",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id: 19,
//   },
//   {
//     name: "Anemone b",
//     part: "Back",
//     cost: 1,
//     attack: 50,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Whenever this Axie draws Anemone restore 20 HP.",
//     class: "Aquatic",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id: 24,
//   },
//   {
//     name: "Babylonia",
//     part: "Horn",
//     cost: 1,
//     attack: 60,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Apply Weak for 4 turns.",
//     class: "Aquatic",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id: 16,
//   },
//   {
//     name: "Blue Moon",
//     part: "Back",
//     cost: 1,
//     attack: 60,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Draw 1 card.",
//     class: "Aquatic",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id: 22,
//   },
//   {
//     name: "Bubblemaker",
//     part: "Ear",
//     cost: 1,
//     attack: "-",
//     shield: 50,
//     heal: "-",
//     cardEffect: " Target any ally. Target gains 2 Bubble.",
//     class: "Aquatic",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id: 9,
//   },
//   {
//     name: "Catfish",
//     part: "Mouth",
//     cost: 1,
//     attack: 60,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Heal HP equal to 50% of unblocked DMG.",
//     class: "Aquatic",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id: 13,
//   },
//   {
//     name: "Clamshell",
//     part: "Horn",
//     cost: 1,
//     attack: 60,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Gain 4 Damage Boost if this attack causes HP loss to target.",
//     class: "Aquatic",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id: 18,
//   },
//   {
//     name: "Clear",
//     part: "Eyes",
//     cost: 0,
//     attack: "-",
//     shield: "-",
//     heal: "-",
//     cardEffect: " Discard up to 2 cards then draw that many. Banish.",
//     class: "Aquatic",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id: 3,
//   },
//   {
//     name: "Gero",
//     part: "Eyes",
//     cost: 1,
//     attack: 60,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Apply Fragile for 4 turns.",
//     class: "Aquatic",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id: 4,
//   },
//   {
//     name: "Gill",
//     part: "Ear",
//     cost: 1,
//     attack: 50,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Your team gains 1 Bubble.",
//     class: "Aquatic",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id: 11,
//   },
//   {
//     name: "Hermit",
//     part: "Back",
//     cost: 1,
//     attack: "-",
//     shield: "-",
//     heal: "-",
//     cardEffect: " Target any ally. Negate 1 next attack on targeted ally.",
//     class: "Aquatic",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id: 21,
//   },
//   {
//     name: "Inkling",
//     part: "Ear",
//     cost: 1,
//     attack: 60,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Shuffle 1 Jinx into your opponent's discard pile.",
//     class: "Aquatic",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id: 10,
//   },
//   {
//     name: "Koi",
//     part: "Tail",
//     cost: 2,
//     attack: 120,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Deal 15 bonus DMG per Aquatic Ally.",
//     class: "Aquatic",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id: 27,
//   },
//   {
//     name: "Lam",
//     part: "Mouth",
//     cost: 1,
//     attack: 65,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Deal 20 bonus DMG if this Axie's HP is above 75%.",
//     class: "Aquatic",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id: 12,
//   },
//   {
//     name: "Nimo e",
//     part: "Ear",
//     cost: 0,
//     attack: "-",
//     shield: "-",
//     heal: 25,
//     cardEffect: " Gain 1 Energy if this Axie's HP is full.",
//     class: "Aquatic",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id: 7,
//   },
//   {
//     name: "Perch",
//     part: "Back",
//     cost: 2,
//     attack: 30,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Deal 4 hits. Prioritize target with lowest HP.",
//     class: "Aquatic",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id: 25,
//   },
//   {
//     name: "Piranha",
//     part: "Mouth",
//     cost: 1,
//     attack: 60,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Apply Bleed for 4 turns.",
//     class: "Aquatic",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id: 15,
//   },
//   {
//     name: "Ranchu",
//     part: "Tail",
//     cost: 2,
//     attack: 50,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Attack all enemies. Apply Weak for 2 turns.",
//     class: "Aquatic",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id: 30,
//   },
//   {
//     name: "Risky Fish",
//     part: "Mouth",
//     cost: 1,
//     attack: 90,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Apply Weak to this Axie for 2 turns.",
//     class: "Aquatic",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id: 14,
//   },
//   {
//     name: "Shoal Star",
//     part: "Horn",
//     cost: 1,
//     attack: 50,
//     shield: "-",
//     heal: "-",
//     cardEffect: " If the target has no more than 120 HP, kill it instantly.",
//     class: "Aquatic",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id: 20,
//   },
//   {
//     name: "Sleepless",
//     part: "Eyes",
//     cost: 1,
//     attack: 60,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Shuffle 1 Daze into your opponent's discard pile.",
//     class: "Aquatic",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id: 2,
//   },
//   {
//     name: "Sponge",
//     part: "Back",
//     cost: 1,
//     attack: "-",
//     shield: 60,
//     heal: "-",
//     cardEffect:
//       " Target any ally. Next turn, apply 5 Damage Boost to shielded target if its shield is broken.",
//     class: "Aquatic",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id: 23,
//   },
//   {
//     name: "Tadpole",
//     part: "Tail",
//     cost: 1,
//     attack: 65,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Shuffle 1 Jinx into your opponent's discard pile.",
//     class: "Aquatic",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id: 29,
//   },
//   {
//     name: "Teal Shell",
//     part: "Horn",
//     cost: 1,
//     attack: "-",
//     shield: "-",
//     heal: "-",
//     cardEffect:
//       " Targeted Ally gains 20 shield for each card played this turn.",
//     class: "Aquatic",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id: 17,
//   },
//   {
//     name: "Telescope",
//     part: "Eyes",
//     cost: 0,
//     attack: "-",
//     shield: "-",
//     heal: "-",
//     cardEffect:
//       " Put 1 Aquatic card from your draw pile into your hand. Banish.",
//     class: "Aquatic",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id: 5,
//   },
//   {
//     name: "Tiny Fan",
//     part: "Ear",
//     cost: 0,
//     attack: "-",
//     shield: "-",
//     heal: "-",
//     cardEffect: " Draw 1 card. Gain 3 Damage Boost.",
//     class: "Aquatic",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id: 8,
//   },
//   {
//     name: "Baby",
//     part: "Eyes",
//     cost: 2,
//     attack: "-",
//     shield: "-",
//     heal: "-",
//     cardEffect: " Attacks deal 33 bonus DMG if HP is above 66%",
//     class: "Aquatic",
//     tag: "Power",
//     img: "o",
//     keyword: "-",
//     id: 1,
//   },
//   {
//     name: "Little Crab",
//     part: "Ear",
//     cost: 1,
//     attack: 80,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Ethereal",
//     class: "Aquatic",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id: 6,
//   },
//   {
//     name: "Puff",
//     part: "Tail",
//     cost: "X",
//     attack: 66,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Retain. Randomly deal X hits.",
//     class: "Aquatic",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id: 26,
//   },
//   //xWrongPNG
//   {
//     name: "Nimo t",
//     part: "Tail",
//     cost: 0,
//     attack: "-",
//     shield: "-",
//     heal: 15,
//     cardEffect: " Gain 1 Energy. Banish.",
//     class: "Aquatic",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id: 28,
//   },
//   //not in collection 310~350
//   {
//     name: "Goldfish",
//     part: "Back",
//     cost: 1,
//     attack: 65,
//     shield: "-",
//     heal: "-",
//     cardEffect: " If Initial, draw 1 card.",
//     class: "Aquatic",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id: 310,
//   },
//   {
//     name: "Navaga",
//     part: "Tail",
//     cost: 1,
//     attack: 70,
//     shield: "-",
//     heal: "-",
//     cardEffect: " If Initial, deal 15 more DMG.",
//     class: "Aquatic",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id: 320,
//   },
//   {
//     name: "Oranda",
//     part: "Horn",
//     cost: 2,
//     attack: 120,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Dispel up to 2 buffs on target.",
//     class: "Aquatic",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id: 330,
//   },
//   {
//     name: "Seaslug",
//     part: "Ear",
//     cost: 2,
//     attack: 110,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Cleanse 2 debuffs. Gain 2 Cleanser.",
//     class: "Aquatic",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id: 340,
//   },
//   {
//     name: "Shrimp",
//     part: "Tail",
//     cost: 1,
//     attack: 70,
//     shield: "-",
//     heal: "-",
//     cardEffect: " If Initial, this attack targets the furthest enemy.",
//     class: "Aquatic",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id: 350,
//   },
// ];

let tagger = [
  {
    name: "Anemone",
    tag: "attack",
  },
  {
    name: "Anemone",
    tag: "attack",
  },
  {
    name: "Baby",
    tag: "power",
  },
  {
    name: "Babylonia",
    tag: "attack",
  },
  {
    name: "Blue Moon",
    tag: "attack",
  },
  {
    name: "Bubblemaker",
    tag: "skill",
  },
  {
    name: "Catfish",
    tag: "attack",
  },
  {
    name: "Clamshell",
    tag: "attack",
  },
  {
    name: "Clear",
    tag: "skill,banish",
  },
  {
    name: "Gero",
    tag: "attack",
  },
  {
    name: "Gill",
    tag: "attack",
  },
  {
    name: "Goldfish",
    tag: "attack",
  },
  {
    name: "Hermit",
    tag: "secret",
  },
  {
    name: "Inkling",
    tag: "attack",
  },
  {
    name: "Koi",
    tag: "attack",
  },
  {
    name: "Lam",
    tag: "attack",
  },
  {
    name: "Navaga",
    tag: "attack",
  },
  {
    name: "Nimo",
    tag: "skill",
  },
  {
    name: "Nimo",
    tag: "skill,banish",
  },
  {
    name: "Oranda",
    tag: "attack",
  },
  {
    name: "Perch",
    tag: "attack",
  },
  {
    name: "Piranha",
    tag: "attack",
  },
  {
    name: "Ranchu",
    tag: "attack",
  },
  {
    name: "Risky Fish",
    tag: "attack",
  },
  {
    name: "Seaslug",
    tag: "attack",
  },
  {
    name: "Shoal Star",
    tag: "attack",
  },
  {
    name: "Shrimp",
    tag: "attack",
  },
  {
    name: "Sleepless",
    tag: "attack",
  },
  {
    name: "Sponge",
    tag: "secret",
  },
  {
    name: "Tadpole",
    tag: "attack",
  },
  {
    name: "Teal Shell",
    tag: "skill",
  },
  {
    name: "Telescope",
    tag: "skill,banish",
  },
  {
    name: "Tiny Fan",
    tag: "skill",
  },
  {
    name: "Little Crab",
    tag: "attack",
  },
  {
    name: "Puff",
    tag: "attack,retain",
  },
];

//
let Aquatic = [
  {
    name: "Anemone h",
    part: "Horn",
    cost: 1,
    attack: 50,
    shield: "-",
    heal: "-",
    cardEffect: " Whenever this Axie draws Anemone restore 20 HP.",
    class: "Aquatic",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 19,
  },
  {
    name: "Anemone b",
    part: "Back",
    cost: 1,
    attack: 50,
    shield: "-",
    heal: "-",
    cardEffect: " Whenever this Axie draws Anemone restore 20 HP.",
    class: "Aquatic",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 24,
  },
  {
    name: "Babylonia",
    part: "Horn",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Apply Weak for 4 turns.",
    class: "Aquatic",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 16,
  },
  {
    name: "Blue Moon",
    part: "Back",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Draw 1 card.",
    class: "Aquatic",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 22,
  },
  {
    name: "Bubblemaker",
    part: "Ear",
    cost: 1,
    attack: "-",
    shield: 50,
    heal: "-",
    cardEffect: " Target any ally. Target gains 2 Bubble.",
    class: "Aquatic",
    tag: "skill",
    img: "o",
    keyword: "-",
    id: 9,
  },
  {
    name: "Catfish",
    part: "Mouth",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Heal HP equal to 50% of unblocked DMG.",
    class: "Aquatic",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 13,
  },
  {
    name: "Clamshell",
    part: "Horn",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Gain 4 Damage Boost if this attack causes HP loss to target.",
    class: "Aquatic",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 18,
  },
  {
    name: "Clear",
    part: "Eyes",
    cost: 0,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect: " Discard up to 2 cards then draw that many. Banish.",
    class: "Aquatic",
    tag: "skill,banish",
    img: "o",
    keyword: "-",
    id: 3,
  },
  {
    name: "Gero",
    part: "Eyes",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Apply Fragile for 4 turns.",
    class: "Aquatic",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 4,
  },
  {
    name: "Gill",
    part: "Ear",
    cost: 1,
    attack: 50,
    shield: "-",
    heal: "-",
    cardEffect: " Your team gains 1 Bubble.",
    class: "Aquatic",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 11,
  },
  {
    name: "Hermit",
    part: "Back",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect: " Target any ally. Negate 1 next attack on targeted ally.",
    class: "Aquatic",
    tag: "secret",
    img: "o",
    keyword: "-",
    id: 21,
  },
  {
    name: "Inkling",
    part: "Ear",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Shuffle 1 Jinx into your opponent's discard pile.",
    class: "Aquatic",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 10,
  },
  {
    name: "Koi",
    part: "Tail",
    cost: 2,
    attack: 120,
    shield: "-",
    heal: "-",
    cardEffect: " Deal 15 bonus DMG per Aquatic Ally.",
    class: "Aquatic",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 27,
  },
  {
    name: "Lam",
    part: "Mouth",
    cost: 1,
    attack: 65,
    shield: "-",
    heal: "-",
    cardEffect: " Deal 20 bonus DMG if this Axie's HP is above 75%.",
    class: "Aquatic",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 12,
  },
  {
    name: "Nimo e",
    part: "Ear",
    cost: 0,
    attack: "-",
    shield: "-",
    heal: 25,
    cardEffect: " Gain 1 Energy if this Axie's HP is full.",
    class: "Aquatic",
    tag: "skill",
    img: "o",
    keyword: "-",
    id: 7,
  },
  {
    name: "Perch",
    part: "Back",
    cost: 2,
    attack: 30,
    shield: "-",
    heal: "-",
    cardEffect: " Deal 4 hits. Prioritize target with lowest HP.",
    class: "Aquatic",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 25,
  },
  {
    name: "Piranha",
    part: "Mouth",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Apply Bleed for 4 turns.",
    class: "Aquatic",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 15,
  },
  {
    name: "Ranchu",
    part: "Tail",
    cost: 2,
    attack: 50,
    shield: "-",
    heal: "-",
    cardEffect: " Attack all enemies. Apply Weak for 2 turns.",
    class: "Aquatic",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 30,
  },
  {
    name: "Risky Fish",
    part: "Mouth",
    cost: 1,
    attack: 90,
    shield: "-",
    heal: "-",
    cardEffect: " Apply Weak to this Axie for 2 turns.",
    class: "Aquatic",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 14,
  },
  {
    name: "Shoal Star",
    part: "Horn",
    cost: 1,
    attack: 50,
    shield: "-",
    heal: "-",
    cardEffect: " If the target has no more than 120 HP, kill it instantly.",
    class: "Aquatic",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 20,
  },
  {
    name: "Sleepless",
    part: "Eyes",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Shuffle 1 Daze into your opponent's discard pile.",
    class: "Aquatic",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 2,
  },
  {
    name: "Sponge",
    part: "Back",
    cost: 1,
    attack: "-",
    shield: 60,
    heal: "-",
    cardEffect:
      " Target any ally. Next turn, apply 5 Damage Boost to shielded target if its shield is broken.",
    class: "Aquatic",
    tag: "secret",
    img: "o",
    keyword: "-",
    id: 23,
  },
  {
    name: "Tadpole",
    part: "Tail",
    cost: 1,
    attack: 65,
    shield: "-",
    heal: "-",
    cardEffect: " Shuffle 1 Jinx into your opponent's discard pile.",
    class: "Aquatic",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 29,
  },
  {
    name: "Teal Shell",
    part: "Horn",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect:
      " Targeted Ally gains 20 shield for each card played this turn.",
    class: "Aquatic",
    tag: "skill",
    img: "o",
    keyword: "-",
    id: 17,
  },
  {
    name: "Telescope",
    part: "Eyes",
    cost: 0,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect:
      " Put 1 Aquatic card from your draw pile into your hand. Banish.",
    class: "Aquatic",
    tag: "skill,banish",
    img: "o",
    keyword: "-",
    id: 5,
  },
  {
    name: "Tiny Fan",
    part: "Ear",
    cost: 0,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect: " Draw 1 card. Gain 3 Damage Boost.",
    class: "Aquatic",
    tag: "skill",
    img: "o",
    keyword: "-",
    id: 8,
  },
  {
    name: "Baby",
    part: "Eyes",
    cost: 2,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect: " Attacks deal 33 bonus DMG if HP is above 66%",
    class: "Aquatic",
    tag: "power",
    img: "o",
    keyword: "-",
    id: 1,
  },
  {
    name: "Little Crab",
    part: "Ear",
    cost: 1,
    attack: 80,
    shield: "-",
    heal: "-",
    cardEffect: " Ethereal",
    class: "Aquatic",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 6,
  },
  {
    name: "Puff",
    part: "Tail",
    cost: "X",
    attack: 66,
    shield: "-",
    heal: "-",
    cardEffect: " Retain. Randomly deal X hits.",
    class: "Aquatic",
    tag: "attack,retain",
    img: "o",
    keyword: "-",
    id: 26,
  },
  {
    name: "Nimo t",
    part: "Tail",
    cost: 0,
    attack: "-",
    shield: "-",
    heal: 15,
    cardEffect: " Gain 1 Energy. Banish.",
    class: "Aquatic",
    tag: "skill",
    img: "o",
    keyword: "-",
    id: 28,
  },
  {
    name: "Goldfish",
    part: "Back",
    cost: 1,
    attack: 65,
    shield: "-",
    heal: "-",
    cardEffect: " If Initial, draw 1 card.",
    class: "Aquatic",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 310,
  },
  {
    name: "Navaga",
    part: "Tail",
    cost: 1,
    attack: 70,
    shield: "-",
    heal: "-",
    cardEffect: " If Initial, deal 15 more DMG.",
    class: "Aquatic",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 320,
  },
  {
    name: "Oranda",
    part: "Horn",
    cost: 2,
    attack: 120,
    shield: "-",
    heal: "-",
    cardEffect: " Dispel up to 2 buffs on target.",
    class: "Aquatic",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 330,
  },
  {
    name: "Seaslug",
    part: "Ear",
    cost: 2,
    attack: 110,
    shield: "-",
    heal: "-",
    cardEffect: " Cleanse 2 debuffs. Gain 2 Cleanser.",
    class: "Aquatic",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 340,
  },
  {
    name: "Shrimp",
    part: "Tail",
    cost: 1,
    attack: 70,
    shield: "-",
    heal: "-",
    cardEffect: " If Initial, this attack targets the furthest enemy.",
    class: "Aquatic",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 350,
  },
];
