let Aquatic = [
  {
    name: "Anemone",
    part: "Horn",
    cost: 1,
    attack: 50,
    shield: "-",
    heal: "-",
    cardEffect: " Whenever this is drawn, heal 20 HP.",
    class: "Aquatic",
    tag: "attack",
    img: "",
    keyword: "-",
  },
  {
    name: "Anemone",
    part: "Back",
    cost: 1,
    attack: 50,
    shield: "-",
    heal: "-",
    cardEffect: " Whenever this is drawn, heal 20 HP.",
    class: "Aquatic",
    tag: "attack",
    img: "",
    keyword: "-",
  },
  {
    name: "Babylonia",
    part: "Horn",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Apply Weak for 4 turns.",
    class: "Aquatic",
    tag: "attack",
    img: "",
    keyword: "-",
  },
  {
    name: "Blue Moon",
    part: "Back",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Draw 1 card.",
    class: "Aquatic",
    tag: "attack",
    img: "",
    keyword: "-",
  },
  {
    name: "Bubblemaker",
    part: "Ear",
    cost: 1,
    attack: "-",
    shield: 50,
    heal: "-",
    cardEffect: " Target any ally. Target gains 2 Bubble.",
    class: "Aquatic",
    tag: "attack",
    img: "",
    keyword: "-",
  },
  {
    name: "Catfish",
    part: "Mouth",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " heal HP equal to 50% of unblocked DMG.",
    class: "Aquatic",
    tag: "attack",
    img: "",
    keyword: "-",
  },
  {
    name: "Clamshell",
    part: "Horn",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Gain 4 Damage Boost if this attack causes HP loss to target.",
    class: "Aquatic",
    tag: "attack",
    img: "",
    keyword: "-",
  },
  {
    name: "Clear",
    part: "Eyes",
    cost: 0,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect: " Discard up to 2 cards then draw that many. Banish.",
    class: "Aquatic",
    tag: "attack",
    img: "",
    keyword: "-",
  },
  {
    name: "Gero",
    part: "Eyes",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Apply Fragile for 4 turns.",
    class: "Aquatic",
    tag: "attack",
    img: "",
    keyword: "-",
  },
  {
    name: "Gill",
    part: "Ear",
    cost: 1,
    attack: 50,
    shield: "-",
    heal: "-",
    cardEffect: " Your team gains 1 Bubble.",
    class: "Aquatic",
    tag: "attack",
    img: "",
    keyword: "-",
  },
  {
    name: "Goldfish",
    part: "Back",
    cost: 1,
    attack: 65,
    shield: "-",
    heal: "-",
    cardEffect: " If Initial, draw 1 card.",
    class: "Aquatic",
    tag: "attack",
    img: "",
    keyword: "-",
  },
  {
    name: "Hermit",
    part: "Back",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect: " Target any ally. Negate 1 next attack on targeted ally.",
    class: "Aquatic",
    tag: "attack",
    img: "",
    keyword: "-",
  },
  {
    name: "Inkling",
    part: "Ear",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Shuffle 1 Jinx into your opponent's discard pile.",
    class: "Aquatic",
    tag: "attack",
    img: "",
    keyword: "-",
  },
  {
    name: "Koi",
    part: "Tail",
    cost: 2,
    attack: 120,
    shield: "-",
    heal: "-",
    cardEffect: " Deal 15 bonus DMG per Aquatic Ally.",
    class: "Aquatic",
    tag: "attack",
    img: "",
    keyword: "-",
  },
  {
    name: "Lam",
    part: "Mouth",
    cost: 1,
    attack: 65,
    shield: "-",
    heal: "-",
    cardEffect: " Deal 20 bonus DMG if this Axie's HP is above 75%.",
    class: "Aquatic",
    tag: "attack",
    img: "",
    keyword: "-",
  },
  {
    name: "Navaga",
    part: "Tail",
    cost: 1,
    attack: 70,
    shield: "-",
    heal: "-",
    cardEffect: " If Initial, deal 15 more DMG.",
    class: "Aquatic",
    tag: "attack",
    img: "",
    keyword: "-",
  },
  {
    name: "Nimo",
    part: "Ear",
    cost: 0,
    attack: "-",
    shield: "-",
    heal: 25,
    cardEffect: " Gain 1 Energy if tthis Axie's HP is full.",
    class: "Aquatic",
    tag: "attack",
    img: "",
    keyword: "-",
  },
  {
    name: "Nimo",
    part: "Tail",
    cost: 0,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect: " Draw 1 Card. Gain 1 Energy. Banish.",
    class: "Aquatic",
    tag: "attack",
    img: "",
    keyword: "-",
  },
  {
    name: "Oranda",
    part: "Horn",
    cost: 2,
    attack: 120,
    shield: "-",
    heal: "-",
    cardEffect: " Dispel up to 2 buffs on target.",
    class: "Aquatic",
    tag: "attack",
    img: "",
    keyword: "-",
  },
  {
    name: "Perch",
    part: "Back",
    cost: 2,
    attack: 30,
    shield: "-",
    heal: "-",
    cardEffect: " Deal 4 hits. Prioritize target with lowest HP.",
    class: "Aquatic",
    tag: "attack",
    img: "",
    keyword: "-",
  },
  {
    name: "Piranha",
    part: "Mouth",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Apply Bleed for 4 turns.",
    class: "Aquatic",
    tag: "attack",
    img: "",
    keyword: "-",
  },
  {
    name: "Ranchu",
    part: "Tail",
    cost: 2,
    attack: 50,
    shield: "-",
    heal: "-",
    cardEffect: " attack all enemies. Apply Weak for 2 turns.",
    class: "Aquatic",
    tag: "attack",
    img: "",
    keyword: "-",
  },
  {
    name: "Risky Fish",
    part: "Mouth",
    cost: 1,
    attack: 90,
    shield: "-",
    heal: "-",
    cardEffect: " Apply Weak to this Axie for 2 turns.",
    class: "Aquatic",
    tag: "attack",
    img: "",
    keyword: "-",
  },
  {
    name: "Seaslug",
    part: "Ear",
    cost: 2,
    attack: 110,
    shield: "-",
    heal: "-",
    cardEffect: " Cleanse 2 debuffs. Gain 2 Cleanser.",
    class: "Aquatic",
    tag: "attack",
    img: "",
    keyword: "-",
  },
  {
    name: "Shoal Star",
    part: "Horn",
    cost: 1,
    attack: 50,
    shield: "-",
    heal: "-",
    cardEffect: " If the target has no more than 120 HP, kill it instantly.",
    class: "Aquatic",
    tag: "attack",
    img: "",
    keyword: "-",
  },
  {
    name: "Shrimp",
    part: "Tail",
    cost: 1,
    attack: 70,
    shield: "-",
    heal: "-",
    cardEffect: " If Initial, this attack targets the furthest enemy.",
    class: "Aquatic",
    tag: "attack",
    img: "",
    keyword: "-",
  },
  {
    name: "Sleepless",
    part: "Eyes",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Shuffle 1 Daze into your opponent's discard pile.",
    class: "Aquatic",
    tag: "attack",
    img: "",
    keyword: "-",
  },
  {
    name: "Sponge",
    part: "Back",
    cost: 1,
    attack: "-",
    shield: 60,
    heal: "-",
    cardEffect:
      " Target any ally. Next turn, apply 5 Damage Boost to shielded target if its shield is broken.",
    class: "Aquatic",
    tag: "attack",
    img: "",
    keyword: "-",
  },
  {
    name: "Tadpole",
    part: "Tail",
    cost: 1,
    attack: 65,
    shield: "-",
    heal: "-",
    cardEffect: " Shuffle 1 Jinx into your opponent's discard pile.",
    class: "Aquatic",
    tag: "attack",
    img: "",
    keyword: "-",
  },
  {
    name: "Teal Shell",
    part: "Horn",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect:
      " Targeted Ally gains 20 shield for each card played this turn.",
    class: "Aquatic",
    tag: "attack",
    img: "",
    keyword: "-",
  },
  {
    name: "Telescope",
    part: "Eyes",
    cost: 0,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect:
      " Put 1 Aquatic card from your draw pile into your hand. Banish.",
    class: "Aquatic",
    tag: "attack",
    img: "",
    keyword: "-",
  },
  {
    name: "Tiny Fan",
    part: "Ear",
    cost: 0,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect: " Draw 1 card. Gain 3 Damage Boost.",
    class: "Aquatic",
    tag: "attack",
    img: "",
    keyword: "-",
  },
];
