//
//9 x
//26 o
let Beast = [
  {
    name: "Arco",
    part: "Horn",
    cost: 1,
    attack: 65,
    shield: "-",
    heal: "-",
    cardEffect: " This does not trigger Secrets.",
    class: "Beast",
    tag: "attack",
    img: "o",
    keyword: "-",
  },
  {
    name: "Axie Kiss",
    part: "Mouth",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect:
      " Target any Enemy. Apply Death Mark for 4 turns if this Axie's HP is below 50%.",
    class: "Beast",
    tag: "attack",
    img: "o",
    keyword: "-",
  },
  {
    name: "Belieber",
    part: "Ear",
    cost: 1,
    attack: 20,
    shield: "-",
    heal: "-",
    cardEffect: " Randomly deal 3 hits. Gain 1 Rage per Enemy hit.",
    class: "Beast",
    tag: "attack",
    img: "o",
    keyword: "-",
  },
  {
    name: "Boomerang",
    part: "Horn",
    cost: 0,
    attack: 25,
    shield: "-",
    heal: "-",
    cardEffect:
      " Return this card to the top of your Draw Pile if your opponent has more cards than you in their hand and discard pile.",
    class: "Beast",
    tag: "attack",
    img: "x",
    keyword: "-",
  },
  {
    name: "Buba Brush",
    part: "Tail",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Gain 2 Rage.",
    class: "Beast",
    tag: "attack",
    img: "x",
    keyword: "-",
  },
  {
    name: "Chubby",
    part: "Eyes",
    cost: 2,
    attack: 50,
    shield: "-",
    heal: "-",
    cardEffect: " attack all enemies.",
    class: "Beast",
    tag: "attack",
    img: "o",
    keyword: "-",
  },
  // {
  //   name: "Confident",
  //   part: "Mouth",
  //   cost: 0,
  //   attack: "-",
  //   shield: "-",
  //   heal: "-",
  //   cardEffect: " Target any ally. Cleanse 1 debuff and grant 2 Rage.",
  //   class: "Beast",
  //   tag: "attack",
  //   img: "",
  //   keyword: "-",
  // },
  {
    name: "Cottontail",
    part: "Tail",
    cost: 0,
    attack: "-",
    shield: "-",
    heal: 25,
    cardEffect: " heal any ally. Gain 1 Energy. Banish.",
    class: "Beast",
    tag: "attack",
    img: "o",
    keyword: "-",
  },
  {
    name: "Dual Blade",
    part: "Horn",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Apply Fragile for 4 turns.",
    class: "Beast",
    tag: "attack",
    img: "o",
    keyword: "-",
  },
  {
    name: "Foxy",
    part: "Mouth",
    cost: 1,
    attack: 65,
    shield: "-",
    heal: "-",
    cardEffect:
      " Retain. Gain 1 Rage. If Retained, +1 Rage when played (cap: 3 rounds).",
    class: "Beast",
    tag: "attack",
    img: "x",
    keyword: "-",
  },
  {
    name: "Furball",
    part: "Back",
    cost: 1,
    attack: 40,
    shield: "-",
    heal: "-",
    cardEffect: " Deal 2 hits.",
    class: "Beast",
    tag: "attack",
    img: "o",
    keyword: "-",
  },
  // {
  //   name: "Gerbil",
  //   part: "Tail",
  //   cost: 1,
  //   attack: 70,
  //   shield: "-",
  //   heal: "-",
  //   cardEffect: " If Initial, this attack targets the second frontmost enemy.",
  //   class: "Beast",
  //   tag: "attack",
  //   img: "",
  //   keyword: "-",
  // },
  {
    name: "Goda",
    part: "Mouth",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Shuffle 1 Void into your opponent's discard pile. Banish.",
    class: "Beast",
    tag: "attack",
    img: "o",
    keyword: "-",
  },
  // {
  //   name: "Hare",
  //   part: "Tail",
  //   cost: 1,
  //   attack: 70,
  //   shield: "-",
  //   heal: "-",
  //   cardEffect: " If Initial, draw 1 card.",
  //   class: "Beast",
  //   tag: "attack",
  //   img: "",
  //   keyword: "-",
  // },
  {
    name: "Hero",
    part: "Back",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Draw 1 card.",
    class: "Beast",
    tag: "attack",
    img: "o",
    keyword: "-",
  },
  {
    name: "Imp",
    part: "Horn",
    cost: 1,
    attack: 70,
    shield: "-",
    heal: "-",
    cardEffect: " cost 0 Energy in Fury Form.",
    class: "Beast",
    tag: "attack",
    img: "o",
    keyword: "-",
  },
  {
    name: "Innocent Lamb",
    part: "Ear",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect:
      " Select and add 1 copy of this Axie's Skill Card to your hand. Banish.",
    class: "Beast",
    tag: "attack",
    img: "o",
    keyword: "-",
  },
  {
    name: "Jaguar",
    part: "Back",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Apply Bleed for 4 turns.",
    class: "Beast",
    tag: "attack",
    img: "o",
    keyword: "-",
  },
  {
    name: "Little Branch",
    part: "Horn",
    cost: 2,
    attack: 130,
    shield: "-",
    heal: "-",
    cardEffect: " Gain 1 Rage per 1 alive Ally (including Summons).",
    class: "Beast",
    tag: "attack",
    img: "o",
    keyword: "-",
  },
  {
    name: "Little Peas",
    part: "Eyes",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Apply Vulnerable for 4 turns.",
    class: "Beast",
    tag: "attack",
    img: "o",
    keyword: "-",
  },
  {
    name: "Lump",
    part: "Horn",
    cost: 1,
    attack: 70,
    shield: "-",
    heal: "-",
    cardEffect: " Target any ally. Target gains 1 Rage.",
    class: "Beast",
    tag: "attack",
    img: "x",
    keyword: "-",
  },
  {
    name: "Merry",
    part: "Horn",
    cost: 1,
    attack: "-",
    shield: 65,
    heal: "-",
    cardEffect: " Target any ally.",
    class: "Beast",
    tag: "attack",
    img: "o",
    keyword: "-",
  },
  {
    name: "Nut Cracker e",
    part: "Ear",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " All Nut Cracker cards of this Axie gain 6 DMG this battle.",
    class: "Beast",
    tag: "attack",
    img: "o",
    keyword: "-",
  },
  {
    name: "Nut Cracker t",
    part: "Tail",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " All Nut Cracker cards of this Axie gain 6 DMG this battle.",
    class: "Beast",
    tag: "attack",
    img: "o",
    keyword: "-",
  },
  {
    name: "Nut Cracker m",
    part: "Mouth",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " All Nut Cracker cards of this Axie gain 6 DMG this battle.",
    class: "Beast",
    tag: "attack",
    img: "o",
    keyword: "-",
  },
  {
    name: "Nyan",
    part: "Ear",
    cost: 1,
    attack: 65,
    shield: "-",
    heal: "-",
    cardEffect: " Deal 15 bonus DMG against Bleeding Enemy.",
    class: "Beast",
    tag: "attack",
    img: "o",
    keyword: "-",
  },
  {
    name: "Platypus",
    part: "Mouth",
    cost: 1,
    attack: "-",
    shield: 30,
    heal: "-",
    cardEffect:
      " Retain. shield your team. If Retained, gain 10 bonus shield.(cap: 3 rounds).",
    class: "Beast",
    tag: "attack",
    img: "x",
    keyword: "-",
  },
  {
    name: "Pocky",
    part: "Horn",
    cost: 1,
    attack: 65,
    shield: "-",
    heal: "-",
    cardEffect: " attack random enemy. Apply Taunt for 2 turns.",
    class: "Beast",
    tag: "attack",
    img: "o",
    keyword: "-",
  },
  {
    name: "Puff",
    part: "Mouth",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " heal HP equal to 50% of unblocked DMG.",
    class: "Beast",
    tag: "attack",
    img: "x",
    keyword: "-",
  },
  // {
  //   name: "Puppy",
  //   part: "Ear",
  //   cost: 1,
  //   attack: "-",
  //   shield: "-",
  //   heal: 26,
  //   cardEffect:
  //     " heal your team. If Initial, remove 1 Curse Card from your deck.",
  //   class: "Beast",
  //   tag: "attack",
  //   img: "",
  //   keyword: "-",
  // },
  {
    name: "Puppy",
    part: "Eyes",
    cost: 0,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect:
      " Put 1 Beast card from your discard pile into your hand. Banish.",
    class: "Beast",
    tag: "attack",
    img: "xOld",
    keyword: "-",
  },
  {
    name: "Rice",
    part: "Tail",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect: " Steal 40 HP. Gain 1 Energy if this Axie's HP is full.",
    class: "Beast",
    tag: "attack",
    img: "o",
    keyword: "-",
  },
  {
    name: "Risky Beast",
    part: "Back",
    cost: 1,
    attack: 90,
    shield: "-",
    heal: "-",
    cardEffect: " Apply Weak to this Axie for 2 turns.",
    class: "Beast",
    tag: "attack",
    img: "o",
    keyword: "-",
  },
  {
    name: "Ronin",
    part: "Back",
    cost: 1,
    attack: 40,
    shield: "-",
    heal: "-",
    cardEffect: " Deal 50% more DMG per energy spent this turn.",
    class: "Beast",
    tag: "attack",
    img: "o",
    keyword: "-",
  },
  {
    name: "Shiba",
    part: "Tail",
    cost: 2,
    attack: 130,
    shield: "-",
    heal: "-",
    cardEffect: " Your team gains 3 Rage if this Axie's HP is below 50%.",
    class: "Beast",
    tag: "attack",
    img: "o",
    keyword: "-",
  },
  {
    name: "Sobby",
    part: "Eyes",
    cost: 0,
    attack: 15,
    shield: "-",
    heal: "-",
    cardEffect: " Your team gains 1 Rage.",
    class: "Beast",
    tag: "attack",
    img: "x",
    keyword: "-",
  },
  {
    name: "Timber",
    part: "Back",
    cost: 1,
    attack: "-",
    shield: 60,
    heal: "-",
    cardEffect:
      " Target any ally. Next turn, after an ally is attacked. Add 1 Lumber shield to your hand.",
    class: "Beast",
    tag: "attack",
    img: "o",
    keyword: "-",
  },
  {
    name: "Zeal",
    part: "Eyes",
    cost: 0,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect: " Put 1 Beast card from your draw pile into your hand. Banish.",
    class: "Beast",
    tag: "Skill",
    img: "o",
    keyword: "-",
  },
  {
    name: "Sparky",
    part: "Eyes",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect: " Gain 4 Rage.",
    class: "Beast",
    tag: "Skill",
    img: "x",
    keyword: "-",
  },
  // {
  //   name: "Zen",
  //   part: "Ear",
  //   cost: 1,
  //   attack: "-",
  //   shield: "-",
  //   heal: 65,
  //   cardEffect: " If Initial, this axie Meditates.",
  //   class: "Beast",
  //   tag: "attack",
  //   img: "",
  //   keyword: "-",
  // },
];
