//
//
//
let Bug = [
  {
    name: "Ant",
    part: "Tail",
    cost: 1,
    attack: "-",
    shield: 40,
    heal: "-",
    cardEffect: " Apply Taunt to this Axie for 4 turns.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Antenna",
    part: "Horn",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect: " Scry 4 cards. Banish.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Beetle Spike",
    part: "Ear",
    cost: 1,
    attack: 45,
    shield: "-",
    heal: "-",
    cardEffect: " Deal pure DMG. Apply Bleed for 4 turns.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Bookworm",
    part: "Eyes",
    cost: 0,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect:
      " Take 1 Bug card from your draw pile and add it to your hand.Banish.",
    class: "Bug",
    tag: "",
    img: " ",
    keyword: "-",
  },
  {
    name: "Brimstone",
    part: "Ears",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect:
      " Retain. Next turn, draw 3 random 0 Energy cards from your deck into your hand.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Buzz Buzz",
    part: "Back",
    cost: 1,
    attack: 20,
    shield: "-",
    heal: "-",
    cardEffect:
      " attack all enemies. Shuffle 1 Daze into your opponent's discard pile.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Caterpillars",
    part: "Horn",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Apply Fear for 4 turns.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Centipede",
    part: "Tail",
    cost: 0,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect:
      " Apply 3 Poison. Add a copy of this card to your discard pile when used.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Cute Bunny",
    part: "Mouth",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Apply Fear for 4 turns.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Ear Breathing",
    part: "Ear",
    cost: 2,
    attack: 30,
    shield: "-",
    heal: "-",
    cardEffect:
      " Randomly Deal 4 hits. Shuffle 1 Goo per enemy hit into opponent's discard pile.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Earwing",
    part: "Ear",
    cost: 1,
    attack: 20,
    shield: "-",
    heal: "-",
    cardEffect: " attack all enemies. Deal 3 bonus DMG per card on your hand.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Fish Snack",
    part: "Tail",
    cost: 1,
    attack: "-",
    shield: 60,
    heal: "-",
    cardEffect:
      " Target any ally. Next turn, after the target is attacked. apply Weak to the attacker for 4 turns.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Garish Worm",
    part: "Back",
    cost: 2,
    attack: 120,
    shield: "-",
    heal: "-",
    cardEffect: " Apply 2 Poison per attack card played this turn.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Gravel Ant",
    part: "Tail",
    cost: 1,
    attack: "-",
    shield: 60,
    heal: "-",
    cardEffect:
      " Target any ally. Next turn, after the target is attacked, apply Fear to the attacker for 4 turns.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Kotaro",
    part: "Eyes",
    cost: 1,
    attack: 50,
    shield: "-",
    heal: "-",
    cardEffect: " attack 1 random enemy and apply Death Mark for 4 turns.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Ladybug Googles",
    part: "Eyes",
    cost: 2,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect: " Each turn, if any Enemy has shield, draw 2 additional cards.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Lagging",
    part: "Horn",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Apply Weak for 4 turns.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Larva",
    part: "Ear",
    cost: 0,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect:
      " Scry 2 cards. Gain 1 Energy if discard 1 skill card upon scrying.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Leaf Bug",
    part: "Horn",
    cost: 1,
    attack: "-",
    shield: 45,
    heal: "-",
    cardEffect: " Whenever this is drawn, gain 30 shield.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Leaf Bug",
    part: "Ear",
    cost: 1,
    attack: "-",
    shield: 45,
    heal: "-",
    cardEffect: " Whenever this is drawn, gain 30 shield.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Leaf Bug",
    part: "Tail",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: 45,
    cardEffect: " Whenever this is drawn, gain 30 shield.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Mosquito",
    part: "Mouth",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " heal HP equal to 50% of unblocked DMG.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Neo",
    part: "Eyes",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect:
      " Look at the top 4 cards of your opponent's draw pile. Banish.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Nerdy",
    part: "Eyes",
    cost: 0,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect: " Discard up to 2 cards then draw that many. Banish.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Parasite",
    part: "Horn",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Look at the top 2 cards of your opponent's draw pile.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Pincer",
    part: "Mouth",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Apply Bleed for 4 turns.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Pliers",
    part: "Horn",
    cost: 1,
    attack: 65,
    shield: "-",
    heal: "-",
    cardEffect: " Deal 25% more DMG to shield.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Pupae",
    part: "Tail",
    cost: 1,
    attack: "-",
    shield: 60,
    heal: "-",
    cardEffect:
      " Target any ally. Next turn, after the target is attacked, it gains 2 Damage Boost.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Sandal",
    part: "Back",
    cost: 2,
    attack: 100,
    shield: "-",
    heal: "-",
    cardEffect:
      " Apply Fear for 2 turns. If target previously has Fear, deal 50% more DMG.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Scarab",
    part: "Back",
    cost: 1,
    attack: 30,
    shield: "-",
    heal: "-",
    cardEffect: " Gain 30 shield. Apply Doubt for 4 turns.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "shield Crusher",
    part: "Tail",
    cost: 1,
    attack: 65,
    shield: "-",
    heal: "-",
    cardEffect: " Deal 25% more DMG to shield.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Snail Shell",
    part: "Back",
    cost: 1,
    attack: "-",
    shield: 60,
    heal: "-",
    cardEffect:
      " Target any ally. Next turn, after the target is attacked, shuffle 1 Goo into your opponent's discard pile.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Spiky Wing",
    part: "Back",
    cost: 1,
    attack: 70,
    shield: "-",
    heal: "-",
    cardEffect: " Deal 25% more DMG to shield.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Square Teeth",
    part: "Mouth",
    cost: 0,
    attack: 25,
    shield: "-",
    heal: "-",
    cardEffect: " If Initial, deal bonus DMG equal to current shield.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Tassels",
    part: "Ear",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: 10,
    cardEffect: " heal your team. heal for 4 bonus HP per Card on your hand.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Termite",
    part: "Ears",
    cost: 0,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect:
      " Innate. Remove 30% of all Enemies' shield. Applies Fragile for 4 turns.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Thorny Caterpillar",
    part: "Tail",
    cost: 2,
    attack: 110,
    shield: "-",
    heal: "-",
    cardEffect: " Deal 50% more DMG against debuffed enemy.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Twin Tail",
    part: "Tail",
    cost: 1,
    attack: 35,
    shield: "-",
    heal: "-",
    cardEffect: " Deal 2 hits.",
    class: "Bug",
    tag: "",
    img: "",
    keyword: "-",
  },
  //
  {
    name: "Ladybug Goggles",
    part: "Eyes",
    cost: 2,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect: " Each turn, if any Enemy has Shield,draw 2 additional Cards.",
    class: "Bug",
    tag: "Power",
    img: "x",
    keyword: "-",
  },
];
