//34張 2022/04/17
//4 not in
//38 o
//0 x [Ladybug Goggles]
//38 all

// let Bug = [
//   {
//     name: "Ant",
//     part: "Tail",
//     cost: 1,
//     attack: "-",
//     shield: 40,
//     heal: "-",
//     cardEffect: " Apply Taunt to this Axie for 4 turns.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:27
//   },
//   {
//     name: "Bookworm",
//     part: "Eyes",
//     cost: 0,
//     attack: "-",
//     shield: "-",
//     heal: "-",
//     cardEffect:
//       " Take 1 Bug card from your draw pile and add it to your hand.Banish.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:2
//   },
//   {
//     name: "Buzz Buzz",
//     part: "Back",
//     cost: 1,
//     attack: 20,
//     shield: "-",
//     heal: "-",
//     cardEffect:
//       " Attack all enemies. Shuffle 1 Daze into your opponent's discard pile.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:22
//   },
//   {
//     name: "Caterpillars",
//     part: "Horn",
//     cost: 1,
//     attack: 60,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Apply Fear for 4 turns.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:34
//   },
//   {
//     name: "Cute Bunny",
//     part: "Mouth",
//     cost: 1,
//     attack: 60,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Apply Fear for 4 turns.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:14
//   },
//   {
//     name: "Earwing",
//     part: "Ear",
//     cost: 1,
//     attack: 20,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Attack all enemies. Deal 3 bonus DMG per card on your hand.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:11
//   },
//   {
//     name: "Fish Snack",
//     part: "Tail",
//     cost: 1,
//     attack: "-",
//     shield: 60,
//     heal: "-",
//     cardEffect:
//       " Target any ally. Next turn, after the target is attacked. apply Weak to the Attacker for 4 turns.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:31
//   },
//   {
//     name: "Garish Worm",
//     part: "Back",
//     cost: 2,
//     attack: 120,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Apply 2 Poison per Attack Card played this turn.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:21
//   },
//   {
//     name: "Gravel Ant",
//     part: "Tail",
//     cost: 1,
//     attack: "-",
//     shield: 60,
//     heal: "-",
//     cardEffect:
//       " Target any ally. Next turn, after the target is attacked, apply Fear to the Attacker for 4 turns.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:32
//   },
//   {
//     name: "Kotaro",
//     part: "Eyes",
//     cost: 1,
//     attack: 50,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Attack 1 random enemy and apply Death Mark for 4 turns.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:5
//   },
//   {
//     name: "Lagging",
//     part: "Horn",
//     cost: 1,
//     attack: 60,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Apply Weak for 4 turns.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:15
//   },
//   {
//     name: "Leaf Bug h",
//     part: "Horn",
//     cost: 1,
//     attack: "-",
//     shield: 55,
//     heal: "-",
//     cardEffect: " Whenever this is drawn, gain 30 shield.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:19
//   },
//   {
//     name: "Leaf Bug e",
//     part: "Ear",
//     cost: 1,
//     attack: "-",
//     shield: 55,
//     heal: "-",
//     cardEffect: " Whenever this is drawn, gain 30 Shield.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:9
//   },
//   {
//     name: "Mosquito",
//     part: "Mouth",
//     cost: 1,
//     attack: 60,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Heal HP equal to 50% of unblocked DMG.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:12
//   },
//   {
//     name: "Neo",
//     part: "Eyes",
//     cost: 1,
//     attack: "-",
//     shield: "-",
//     heal: "-",
//     cardEffect:
//       " Look at the top 4 cards of your opponent's draw pile. Banish.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:3
//   },
//   {
//     name: "Nerdy",
//     part: "Eyes",
//     cost: 0,
//     attack: "-",
//     shield: "-",
//     heal: "-",
//     cardEffect: " Discard up to 2 cards then draw that many. Banish.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:4
//   },
//   {
//     name: "Parasite",
//     part: "Horn",
//     cost: 1,
//     attack: 60,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Look at the top 2 cards of your opponent's draw pile.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:18
//   },
//   {
//     name: "Pincer",
//     part: "Mouth",
//     cost: 1,
//     attack: 60,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Apply Bleed for 4 turns.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:13
//   },
//   {
//     name: "Pliers",
//     part: "Horn",
//     cost: 1,
//     attack: 65,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Deal 25% more DMG to shield.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:17
//   },
//   {
//     name: "Pupae",
//     part: "Tail",
//     cost: 1,
//     attack: "-",
//     shield: 60,
//     heal: "-",
//     cardEffect:
//       " Target any ally. Next turn, after the target is attacked, it gains 2 Damage Boost.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:33
//   },
//   {
//     name: "Sandal",
//     part: "Back",
//     cost: 2,
//     attack: 100,
//     shield: "-",
//     heal: "-",
//     cardEffect:
//       " Apply Fear for 2 turns. If target previously has Fear, deal 50% more DMG.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:23
//   },
//   {
//     name: "Scarab",
//     part: "Back",
//     cost: 1,
//     attack: 30,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Gain 30 Shield. Apply Doubt for 4 turns.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:24
//   },
//   {
//     name: "Snail Shell",
//     part: "Back",
//     cost: 1,
//     attack: "-",
//     shield: 60,
//     heal: "-",
//     cardEffect:
//       " Target any ally. Next turn, after the target is attacked, shuffle 1 Goo into your opponent's discard pile.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:20
//   },
//   {
//     name: "Spiky Wing",
//     part: "Back",
//     cost: 1,
//     attack: 70,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Deal 25% more DMG to shield.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:25
//   },
//   {
//     name: "Tassels",
//     part: "Ear",
//     cost: 1,
//     attack: "-",
//     shield: "-",
//     heal: 10,
//     cardEffect: " Heal your team. heal for 4 bonus HP per Card on your hand.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:10
//   },
//   {
//     name: "Thorny Caterpillar",
//     part: "Tail",
//     cost: 2,
//     attack: 110,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Deal 50% more DMG against debuffed enemy.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:16
//   },
//   {
//     name: "Twin Tail",
//     part: "Tail",
//     cost: 1,
//     attack: 35,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Deal 2 hits.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:29
//   },
//   //
//   {
//     name: "Termite",
//     part: "Ears",
//     cost: 0,
//     attack: "-",
//     shield: "-",
//     heal: "-",
//     cardEffect:
//       " Innate. Remove 30% of all Enemies' Shield. Applies Fragile for 4 turns.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:6
//   },
//   {
//     name: "Centipede",
//     part: "Tail",
//     cost: 0,
//     attack: "-",
//     shield: "-",
//     heal: "-",
//     cardEffect:
//       " Apply 3 Poison. Add a copy of this card to your discard pile when used.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:26
//   },
//   {
//     name: "Shield Crusher",
//     part: "Tail",
//     cost: 1,
//     attack: 65,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Deal 25% more DMG to shield.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:28
//   },
//   {
//     name: "Leaf Bug t",
//     part: "Tail",
//     cost: 1,
//     attack: "-",
//     shield: "-",
//     heal: 45,
//     cardEffect: " Whenever this is drawn, gain 30 Shield.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:30
//   },
//   {
//     name: "Brimstone",
//     part: "Ears",
//     cost: 1,
//     attack: "-",
//     shield: "-",
//     heal: "-",
//     cardEffect:
//       " Retain. Next turn, draw 3 random 0 Energy cards from your deck into your hand.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:7
//   },
//   {
//     name: "Ear Breathing",
//     part: "Ear",
//     cost: 2,
//     attack: 30,
//     shield: "-",
//     heal: "-",
//     cardEffect:
//       " Randomly Deal 4 hits. Shuffle 1 Goo per enemy hit into opponent's discard pile.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:8
//   },
//   //x
//   {
//     name: "Ladybug Goggles",
//     part: "Eyes",
//     cost: 2,
//     attack: "-",
//     shield: "-",
//     heal: "-",
//     cardEffect: " Each turn, if any Enemy has Shield,draw 2 additional Cards.",
//     class: "Bug",
//     tag: "Power",
//     img: "o",
//     keyword: "-",
//     id:1,
//   },
//   // not in 350~380 x4
//   {
//     name: "Antenna",
//     part: "Horn",
//     cost: 1,
//     attack: "-",
//     shield: "-",
//     heal: "-",
//     cardEffect: " Scry 4 cards. Banish.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:350
//   },
//   {
//     name: "Beetle Spike",
//     part: "Ear",
//     cost: 1,
//     attack: 45,
//     shield: "-",
//     heal: "-",
//     cardEffect: " Deal pure DMG. Apply Bleed for 4 turns.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:360
//   },
//   {
//     name: "Larva",
//     part: "Ear",
//     cost: 0,
//     attack: "-",
//     shield: "-",
//     heal: "-",
//     cardEffect:
//       " Scry 2 cards. Gain 1 Energy if discard 1 skill card upon scrying.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:370
//   },
//   {
//     name: "Square Teeth",
//     part: "Mouth",
//     cost: 0,
//     attack: 25,
//     shield: "-",
//     heal: "-",
//     cardEffect: " If Initial, deal bonus DMG equal to current Shield.",
//     class: "Bug",
//     tag: "",
//     img: "o",
//     keyword: "-",
//     id:380
//   },
// ];

let Bug = [
  {
    name: "Ant",
    part: "Tail",
    cost: 1,
    attack: "-",
    shield: 40,
    heal: "-",
    cardEffect: " Apply Taunt to this Axie for 4 turns.",
    class: "Bug",
    tag: "skill",
    img: "o",
    keyword: "-",
    id: 27,
  },
  {
    name: "Bookworm",
    part: "Eyes",
    cost: 0,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect:
      " Take 1 Bug card from your draw pile and add it to your hand.Banish.",
    class: "Bug",
    tag: "skill,banish",
    img: "o",
    keyword: "-",
    id: 2,
  },
  {
    name: "Buzz Buzz",
    part: "Back",
    cost: 1,
    attack: 20,
    shield: "-",
    heal: "-",
    cardEffect:
      " Attack all enemies. Shuffle 1 Daze into your opponent's discard pile.",
    class: "Bug",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 22,
  },
  {
    name: "Caterpillars",
    part: "Horn",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Apply Fear for 4 turns.",
    class: "Bug",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 34,
  },
  {
    name: "Cute Bunny",
    part: "Mouth",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Apply Fear for 4 turns.",
    class: "Bug",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 14,
  },
  {
    name: "Earwing",
    part: "Ear",
    cost: 1,
    attack: 20,
    shield: "-",
    heal: "-",
    cardEffect: " Attack all enemies. Deal 3 bonus DMG per card on your hand.",
    class: "Bug",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 11,
  },
  {
    name: "Fish Snack",
    part: "Tail",
    cost: 1,
    attack: "-",
    shield: 60,
    heal: "-",
    cardEffect:
      " Target any ally. Next turn, after the target is attacked. apply Weak to the Attacker for 4 turns.",
    class: "Bug",
    tag: "secret",
    img: "o",
    keyword: "-",
    id: 31,
  },
  {
    name: "Garish Worm",
    part: "Back",
    cost: 2,
    attack: 120,
    shield: "-",
    heal: "-",
    cardEffect: " Apply 2 Poison per Attack Card played this turn.",
    class: "Bug",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 21,
  },
  {
    name: "Gravel Ant",
    part: "Tail",
    cost: 1,
    attack: "-",
    shield: 60,
    heal: "-",
    cardEffect:
      " Target any ally. Next turn, after the target is attacked, apply Fear to the Attacker for 4 turns.",
    class: "Bug",
    tag: "secret",
    img: "o",
    keyword: "-",
    id: 32,
  },
  {
    name: "Kotaro",
    part: "Eyes",
    cost: 1,
    attack: 50,
    shield: "-",
    heal: "-",
    cardEffect: " Attack 1 random enemy and apply Death Mark for 4 turns.",
    class: "Bug",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 5,
  },
  {
    name: "Lagging",
    part: "Horn",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Apply Weak for 4 turns.",
    class: "Bug",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 15,
  },
  {
    name: "Leaf Bug h",
    part: "Horn",
    cost: 1,
    attack: "-",
    shield: 55,
    heal: "-",
    cardEffect: " Whenever this is drawn, gain 30 shield.",
    class: "Bug",
    tag: "skill",
    img: "o",
    keyword: "-",
    id: 19,
  },
  {
    name: "Leaf Bug e",
    part: "Ear",
    cost: 1,
    attack: "-",
    shield: 55,
    heal: "-",
    cardEffect: " Whenever this is drawn, gain 30 Shield.",
    class: "Bug",
    tag: "skill",
    img: "o",
    keyword: "-",
    id: 9,
  },
  {
    name: "Mosquito",
    part: "Mouth",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Heal HP equal to 50% of unblocked DMG.",
    class: "Bug",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 12,
  },
  {
    name: "Neo",
    part: "Eyes",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect:
      " Look at the top 4 cards of your opponent's draw pile. Banish.",
    class: "Bug",
    tag: "skill,banish",
    img: "o",
    keyword: "-",
    id: 3,
  },
  {
    name: "Nerdy",
    part: "Eyes",
    cost: 0,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect: " Discard up to 2 cards then draw that many. Banish.",
    class: "Bug",
    tag: "skill,banish",
    img: "o",
    keyword: "-",
    id: 4,
  },
  {
    name: "Parasite",
    part: "Horn",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Look at the top 2 cards of your opponent's draw pile.",
    class: "Bug",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 18,
  },
  {
    name: "Pincer",
    part: "Mouth",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Apply Bleed for 4 turns.",
    class: "Bug",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 13,
  },
  {
    name: "Pliers",
    part: "Horn",
    cost: 1,
    attack: 65,
    shield: "-",
    heal: "-",
    cardEffect: " Deal 25% more DMG to shield.",
    class: "Bug",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 17,
  },
  {
    name: "Pupae",
    part: "Tail",
    cost: 1,
    attack: "-",
    shield: 60,
    heal: "-",
    cardEffect:
      " Target any ally. Next turn, after the target is attacked, it gains 2 Damage Boost.",
    class: "Bug",
    tag: "secret",
    img: "o",
    keyword: "-",
    id: 33,
  },
  {
    name: "Sandal",
    part: "Back",
    cost: 2,
    attack: 100,
    shield: "-",
    heal: "-",
    cardEffect:
      " Apply Fear for 2 turns. If target previously has Fear, deal 50% more DMG.",
    class: "Bug",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 23,
  },
  {
    name: "Scarab",
    part: "Back",
    cost: 1,
    attack: 30,
    shield: "-",
    heal: "-",
    cardEffect: " Gain 30 Shield. Apply Doubt for 4 turns.",
    class: "Bug",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 24,
  },
  {
    name: "Snail Shell",
    part: "Back",
    cost: 1,
    attack: "-",
    shield: 60,
    heal: "-",
    cardEffect:
      " Target any ally. Next turn, after the target is attacked, shuffle 1 Goo into your opponent's discard pile.",
    class: "Bug",
    tag: "secret",
    img: "o",
    keyword: "-",
    id: 20,
  },
  {
    name: "Spiky Wing",
    part: "Back",
    cost: 1,
    attack: 70,
    shield: "-",
    heal: "-",
    cardEffect: " Deal 25% more DMG to shield.",
    class: "Bug",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 25,
  },
  {
    name: "Tassels",
    part: "Ear",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: 10,
    cardEffect: " Heal your team. heal for 4 bonus HP per Card on your hand.",
    class: "Bug",
    tag: "skill",
    img: "o",
    keyword: "-",
    id: 10,
  },
  {
    name: "Thorny Caterpillar",
    part: "Tail",
    cost: 2,
    attack: 110,
    shield: "-",
    heal: "-",
    cardEffect: " Deal 50% more DMG against debuffed enemy.",
    class: "Bug",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 16,
  },
  {
    name: "Twin Tail",
    part: "Tail",
    cost: 1,
    attack: 35,
    shield: "-",
    heal: "-",
    cardEffect: " Deal 2 hits.",
    class: "Bug",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 29,
  },
  {
    name: "Termite",
    part: "Ears",
    cost: 0,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect:
      " Innate. Remove 30% of all Enemies' Shield. Applies Fragile for 4 turns.",
    class: "Bug",
    tag: "skill,innate",
    img: "o",
    keyword: "-",
    id: 6,
  },
  {
    name: "Centipede",
    part: "Tail",
    cost: 0,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect:
      " Apply 3 Poison. Add a copy of this card to your discard pile when used.",
    class: "Bug",
    tag: "skill",
    img: "o",
    keyword: "-",
    id: 26,
  },
  {
    name: "Shield Crusher",
    part: "Tail",
    cost: 1,
    attack: 65,
    shield: "-",
    heal: "-",
    cardEffect: " Deal 25% more DMG to shield.",
    class: "Bug",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 28,
  },
  {
    name: "Leaf Bug t",
    part: "Tail",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: 45,
    cardEffect: " Whenever this is drawn, gain 30 Shield.",
    class: "Bug",
    tag: "skill",
    img: "o",
    keyword: "-",
    id: 30,
  },
  {
    name: "Brimstone",
    part: "Ears",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect:
      " Retain. Next turn, draw 3 random 0 Energy cards from your deck into your hand.",
    class: "Bug",
    tag: "skill,retain",
    img: "o",
    keyword: "-",
    id: 7,
  },
  {
    name: "Ear Breathing",
    part: "Ear",
    cost: 2,
    attack: 30,
    shield: "-",
    heal: "-",
    cardEffect:
      " Randomly Deal 4 hits. Shuffle 1 Goo per enemy hit into opponent's discard pile.",
    class: "Bug",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 8,
  },
  {
    name: "Ladybug Goggles",
    part: "Eyes",
    cost: 2,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect: " Each turn, if any Enemy has Shield,draw 2 additional Cards.",
    class: "Bug",
    tag: "power",
    img: "o",
    keyword: "-",
    id: 1,
  },
  {
    name: "Antenna",
    part: "Horn",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect: " Scry 4 cards. Banish.",
    class: "Bug",
    tag: "skill,banish",
    img: "o",
    keyword: "-",
    id: 350,
  },
  {
    name: "Beetle Spike",
    part: "Ear",
    cost: 1,
    attack: 45,
    shield: "-",
    heal: "-",
    cardEffect: " Deal pure DMG. Apply Bleed for 4 turns.",
    class: "Bug",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 360,
  },
  {
    name: "Larva",
    part: "Ear",
    cost: 0,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect:
      " Scry 2 cards. Gain 1 Energy if discard 1 skill card upon scrying.",
    class: "Bug",
    tag: "skill",
    img: "o",
    keyword: "-",
    id: 370,
  },
  {
    name: "Square Teeth",
    part: "Mouth",
    cost: 0,
    attack: 25,
    shield: "-",
    heal: "-",
    cardEffect: " If Initial, deal bonus DMG equal to current Shield.",
    class: "Bug",
    tag: "attack",
    img: "o",
    keyword: "-",
    id: 380,
  },
];
