const template = {
  img: [],
  keyword: [],
  tag: [
    "Attack",
    "Skill",
    "Sevret",
    "Power",
    "Banish",
    "Ethereal",
    "Innate",
    "Retain",
  ],
  keyword: [],
  part: ["Eyes", "Mouth", "Ears", "Horn", "Back", "Tail"],
  class: [
    "Beast",
    "Bug",
    "Bird",
    "Plant",
    "Aquatic",
    "Reptile",
    "Mech",
    "Dawn",
    "Dusk",
  ],
};

const in_headers = [
  {
    text: "Card Name",
    align: "start",
    sortable: false,
    value: "Name",
    filterable: true,
    width: "20%",
  },
  { text: "Cost", value: "Cost", filterable: true },
  { text: "Attack", value: "Attack", filterable: false },
  { text: "Shield", value: "Shield", filterable: false },
  { text: "Heal", value: "Heal", filterable: false },
  // { text: "Card Tag", value: "Tag", filterable: true },
  //   { text: "Axie Part", value: "Part", filterable: false },
  //   { text: "Card Effect", value: "CardEffect", filterable: false },
  { text: "Card Class", value: "Class", filterable: true },
];

const in_cardClass = [
  "Beast",
  "Bug",
  "Bird",
  "Plant",
  "Aquatic",
  "Reptile",
  "Mech",
  "Dawn",
  "Dusk",
];
let Aquatic = [
  {
    Name: "Anemone",
    Part: "Horn",
    Cost: 1,
    Attack: 50,
    Shield: "-",
    Heal: "-",
    CardEffect: " Whenever this is drawn, heal 20 HP.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Anemone",
    Part: "Back",
    Cost: 1,
    Attack: 50,
    Shield: "-",
    Heal: "-",
    CardEffect: " Whenever this is drawn, heal 20 HP.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Babylonia",
    Part: "Horn",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " Apply Weak for 4 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Blue Moon",
    Part: "Back",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " Draw 1 card.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Bubblemaker",
    Part: "Ear",
    Cost: 1,
    Attack: "-",
    Shield: 50,
    Heal: "-",
    CardEffect: " Target any ally. Target gains 2 Bubble.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Catfish",
    Part: "Mouth",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " Heal HP equal to 50% of unblocked DMG.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Clamshell",
    Part: "Horn",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " Gain 4 Damage Boost if this attack causes HP loss to target.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Clear",
    Part: "Eyes",
    Cost: 0,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect: " Discard up to 2 cards then draw that many. Banish.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Gero",
    Part: "Eyes",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " Apply Fragile for 4 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Gill",
    Part: "Ear",
    Cost: 1,
    Attack: 50,
    Shield: "-",
    Heal: "-",
    CardEffect: " Your team gains 1 Bubble.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Goldfish",
    Part: "Back",
    Cost: 1,
    Attack: 65,
    Shield: "-",
    Heal: "-",
    CardEffect: " If Initial, draw 1 card.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Hermit",
    Part: "Back",
    Cost: 1,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect: " Target any ally. Negate 1 next attack on targeted ally.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Inkling",
    Part: "Ear",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " Shuffle 1 Jinx into your opponent's discard pile.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Koi",
    Part: "Tail",
    Cost: 2,
    Attack: 120,
    Shield: "-",
    Heal: "-",
    CardEffect: " Deal 15 bonus DMG per Aquatic Ally.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Lam",
    Part: "Mouth",
    Cost: 1,
    Attack: 65,
    Shield: "-",
    Heal: "-",
    CardEffect: " Deal 20 bonus DMG if this Axie's HP is above 75%.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Navaga",
    Part: "Tail",
    Cost: 1,
    Attack: 70,
    Shield: "-",
    Heal: "-",
    CardEffect: " If Initial, deal 15 more DMG.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Nimo",
    Part: "Ear",
    Cost: 0,
    Attack: "-",
    Shield: "-",
    Heal: 25,
    CardEffect: " Gain 1 Energy if tthis Axie's HP is full.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Nimo",
    Part: "Tail",
    Cost: 0,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect: " Draw 1 Card. Gain 1 Energy. Banish.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Oranda",
    Part: "Horn",
    Cost: 2,
    Attack: 120,
    Shield: "-",
    Heal: "-",
    CardEffect: " Dispel up to 2 buffs on target.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Perch",
    Part: "Back",
    Cost: 2,
    Attack: 30,
    Shield: "-",
    Heal: "-",
    CardEffect: " Deal 4 hits. Prioritize target with lowest HP.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Piranha",
    Part: "Mouth",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " Apply Bleed for 4 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Ranchu",
    Part: "Tail",
    Cost: 2,
    Attack: 50,
    Shield: "-",
    Heal: "-",
    CardEffect: " Attack all enemies. Apply Weak for 2 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Risky Fish",
    Part: "Mouth",
    Cost: 1,
    Attack: 90,
    Shield: "-",
    Heal: "-",
    CardEffect: " Apply Weak to this Axie for 2 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Seaslug",
    Part: "Ear",
    Cost: 2,
    Attack: 110,
    Shield: "-",
    Heal: "-",
    CardEffect: " Cleanse 2 debuffs. Gain 2 Cleanser.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Shoal Star",
    Part: "Horn",
    Cost: 1,
    Attack: 50,
    Shield: "-",
    Heal: "-",
    CardEffect: " If the target has no more than 120 HP, kill it instantly.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Shrimp",
    Part: "Tail",
    Cost: 1,
    Attack: 70,
    Shield: "-",
    Heal: "-",
    CardEffect: " If Initial, this attack targets the furthest enemy.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Sleepless",
    Part: "Eyes",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " Shuffle 1 Daze into your opponent's discard pile.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Sponge",
    Part: "Back",
    Cost: 1,
    Attack: "-",
    Shield: 60,
    Heal: "-",
    CardEffect:
      " Target any ally. Next turn, apply 5 Damage Boost to shielded target if its shield is broken.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Tadpole",
    Part: "Tail",
    Cost: 1,
    Attack: 65,
    Shield: "-",
    Heal: "-",
    CardEffect: " Shuffle 1 Jinx into your opponent's discard pile.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Teal Shell",
    Part: "Horn",
    Cost: 1,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Targeted Ally gains 20 shield for each card played this turn.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Telescope",
    Part: "Eyes",
    Cost: 0,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Put 1 Aquatic card from your draw pile into your hand. Banish.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Tiny Fan",
    Part: "Ear",
    Cost: 0,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect: " Draw 1 card. Gain 3 Damage Boost.",
    Class: "Beast",
    Tag: "Attack",
  },
];
let Beast = [
  {
    Name: "Acro",
    Part: "Horn",
    Cost: 1,
    Attack: 65,
    Shield: "-",
    Heal: "-",
    CardEffect: " This does not trigger Secrets.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Axie Kiss",
    Part: "Mouth",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Target any Enemy. Apply Death Mark for 4 turns if this Axie's HP is below 50%.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Belieber",
    Part: "Ear",
    Cost: 1,
    Attack: 20,
    Shield: "-",
    Heal: "-",
    CardEffect: " Randomly deal 3 hits. Gain 1 Rage per Enemy hit.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Boomerang",
    Part: "Horn",
    Cost: 0,
    Attack: 25,
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Return this card to the top of your Draw Pile if your opponent has more cards than you in their hand and discard pile.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Buba Brush",
    Part: "Tail",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " Gain 2 Rage.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Chubby",
    Part: "Eyes",
    Cost: 2,
    Attack: 50,
    Shield: "-",
    Heal: "-",
    CardEffect: " Attack all enemies.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Confident",
    Part: "Mouth",
    Cost: 0,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect: " Target any ally. Cleanse 1 debuff and grant 2 Rage.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Cottontail",
    Part: "Tail",
    Cost: 0,
    Attack: "-",
    Shield: "-",
    Heal: 25,
    CardEffect: " Heal any ally. Gain 1 Energy. Banish.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Dual Blade",
    Part: "Horn",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " Apply Fragile for 4 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Foxy",
    Part: "Mouth",
    Cost: 1,
    Attack: 65,
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Retain. Gain 1 Rage. If Retained, +1 Rage when played (cap: 3 rounds).",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Furball",
    Part: "Back",
    Cost: 1,
    Attack: 40,
    Shield: "-",
    Heal: "-",
    CardEffect: " Deal 2 hits.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Gerbil",
    Part: "Tail",
    Cost: 1,
    Attack: 70,
    Shield: "-",
    Heal: "-",
    CardEffect: " If Initial, this attack targets the second frontmost enemy.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Goda",
    Part: "Mouth",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " Shuffle 1 Void into your opponent's discard pile. Banish.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Hare",
    Part: "Tail",
    Cost: 1,
    Attack: 70,
    Shield: "-",
    Heal: "-",
    CardEffect: " If Initial, draw 1 card.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Hero",
    Part: "Back",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " Draw 1 card.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Imp",
    Part: "Horn",
    Cost: 1,
    Attack: 70,
    Shield: "-",
    Heal: "-",
    CardEffect: " Cost 0 Energy in Fury Form.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Innocent Lamb",
    Part: "Ear",
    Cost: 1,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Select and add 1 copy of this Axie's Skill Card to your hand. Banish.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Jaguar",
    Part: "Back",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " Apply Bleed for 4 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Little Branch",
    Part: "Horn",
    Cost: 2,
    Attack: 130,
    Shield: "-",
    Heal: "-",
    CardEffect: " Gain 1 Rage per 1 alive Ally (including Summons).",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Little Peas",
    Part: "Eyes",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " Apply Vulnerable for 4 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Lump",
    Part: "Horn",
    Cost: 1,
    Attack: 70,
    Shield: "-",
    Heal: "-",
    CardEffect: " Target any ally. Target gains 1 Rage.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Merry",
    Part: "Horn",
    Cost: 1,
    Attack: "-",
    Shield: 65,
    Heal: "-",
    CardEffect: " Target any ally.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Nut Cracker",
    Part: "Ear",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " All Nut Cracker cards of this Axie gain 6 DMG this battle.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Nut Cracker",
    Part: "Tail",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " All Nut Cracker cards of this Axie gain 6 DMG this battle.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Nut Cracker",
    Part: "Mouth",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " All Nut Cracker cards of this Axie gain 6 DMG this battle.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Nyan",
    Part: "Ear",
    Cost: 1,
    Attack: 65,
    Shield: "-",
    Heal: "-",
    CardEffect: " Deal 15 bonus DMG against Bleeding Enemy.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Platypus",
    Part: "Mouth",
    Cost: 1,
    Attack: "-",
    Shield: 30,
    Heal: "-",
    CardEffect:
      " Retain. Shield your team. If Retained, gain 10 bonus Shield.(cap: 3 rounds).",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Pocky",
    Part: "Horn",
    Cost: 1,
    Attack: 65,
    Shield: "-",
    Heal: "-",
    CardEffect: " Attack random enemy. Apply Taunt for 2 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Puff",
    Part: "Mouth",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " Heal HP equal to 50% of unblocked DMG.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Puppy",
    Part: "Ear",
    Cost: 1,
    Attack: "-",
    Shield: "-",
    Heal: 26,
    CardEffect:
      " Heal your team. If Initial, remove 1 Curse Card from your deck.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Puppy",
    Part: "Eyes",
    Cost: 0,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Put 1 Beast card from your discard pile into your hand. Banish.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Rice",
    Part: "Tail",
    Cost: 1,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect: " Steal 40 HP. Gain 1 Energy if this Axie's HP is full.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Risky Beast",
    Part: "Back",
    Cost: 1,
    Attack: 90,
    Shield: "-",
    Heal: "-",
    CardEffect: " Apply Weak to this Axie for 2 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Ronin",
    Part: "Back",
    Cost: 1,
    Attack: 40,
    Shield: "-",
    Heal: "-",
    CardEffect: " Deal 50% more DMG per energy spent this turn.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Shiba",
    Part: "Tail",
    Cost: 2,
    Attack: 130,
    Shield: "-",
    Heal: "-",
    CardEffect: " Your team gains 3 Rage if this Axie's HP is below 50%.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Sobby",
    Part: "Eyes",
    Cost: 0,
    Attack: 15,
    Shield: "-",
    Heal: "-",
    CardEffect: " Your team gains 1 Rage.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Timber",
    Part: "Back",
    Cost: 1,
    Attack: "-",
    Shield: 60,
    Heal: "-",
    CardEffect:
      " Target any ally. Next turn, after an ally is attacked. Add 1 Lumber Shield to your hand.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Zeal",
    Part: "Eyes",
    Cost: 0,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect: " Put 1 Beast card from your draw pile into your hand. Banish.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Zen",
    Part: "Ear",
    Cost: 1,
    Attack: "-",
    Shield: "-",
    Heal: 65,
    CardEffect: " If Initial, this axie Meditates.",
    Class: "Beast",
    Tag: "Attack",
  },
];
let Bird = [
  {
    Name: "Balloon",
    Part: "Back",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " Apply Fear for 4 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Big Sister",
    Part: "Horn",
    Cost: 0,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect: " Discard 1 copy of Lil Bro.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Cloud",
    Part: "Tail",
    Cost: 1,
    Attack: 70,
    Shield: "-",
    Heal: "-",
    CardEffect: " This attack targets the frontmost non-summoned enemy.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Concentrate",
    Part: "Eyes",
    Cost: 2,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect: " All Multihit Attack cards of this Axie gain +18 DMG.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Cuckoo",
    Part: "Horn",
    Cost: 1,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Target an ally. Remove Sleep. The next attack of the target his turn deals 50 more DMG.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Cupid",
    Part: "Back",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " Apply Bleed for 4 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Curly",
    Part: "Ear",
    Cost: 1,
    Attack: 65,
    Shield: "-",
    Heal: "-",
    CardEffect: " Deal 25% more DMG to shield.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Doubletalk",
    Part: "Mouth",
    Cost: 1,
    Attack: 65,
    Shield: "-",
    Heal: "-",
    CardEffect: " if Initial, apply Sleep for 4 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Early Bird",
    Part: "Ear",
    Cost: 1,
    Attack: 65,
    Shield: "-",
    Heal: "-",
    CardEffect: " If Initial, draw 1 card.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Eggshell",
    Part: "Horn",
    Cost: 1,
    Attack: 75,
    Shield: "-",
    Heal: "-",
    CardEffect: " Apply Taunt to this Axie for 2 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Feather Dagger",
    Part: "Mouth",
    Cost: 0,
    Attack: 10,
    Shield: "-",
    Heal: "-",
    CardEffect: " Deal 2 hits.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Feather Fan",
    Part: "Tail",
    Cost: 2,
    Attack: 35,
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Randomly deal 4 hits. Your team gains 1 Feather per enemy hit.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Feather Spear",
    Part: "Horn",
    Cost: 1,
    Attack: 65,
    Shield: "-",
    Heal: "-",
    CardEffect: " Deal 20 more DMG for each Spear card used this turn.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Granma's Fan",
    Part: "Tail",
    Cost: 1,
    Attack: 25,
    Shield: "-",
    Heal: "-",
    CardEffect: " Innate. Attack all enemies. Apply Vulnerable for 4 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Hungry Bird",
    Part: "Mouth",
    Cost: 1,
    Attack: 65,
    Shield: "-",
    Heal: "-",
    CardEffect: " If Initial, heal 15 HP.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Kestrel",
    Part: "Horn",
    Cost: 1,
    Attack: 50,
    Shield: "-",
    Heal: "-",
    CardEffect: " Apply Disarmed for 4 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Kingfisher",
    Part: "Back",
    Cost: 1,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Target any ally. Next attack against the target is reflected for 85 DMG.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Lil Bro",
    Part: "Back",
    Cost: 1,
    Attack: 30,
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Innate. Randomly deal 2 hits. Discard 1 copy of Feather Dagger per Enemy hit.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Little Owl",
    Part: "Ear",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " All Little Owl cards of this Axie gain 6 DMG this battle.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Little Owl",
    Part: "Eyes",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " All Little Owl cards of this Axie gain 6 DMG this battle.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Little Owl",
    Part: "Mouth",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " All Little Owl cards of this Axie gain 6 DMG this battle.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Lucas",
    Part: "Eyes",
    Cost: 0,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect: " Put 1 Bird card from your draw pile into your hand. Banish.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Mavis",
    Part: "Eyes",
    Cost: 1,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect: " Summon 1 Mavis.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Paper Wing",
    Part: "Back",
    Cost: 1,
    Attack: 50,
    Shield: "-",
    Heal: "-",
    CardEffect: " Retain. Deal 9 bonus DMG per card in your hand.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Passion",
    Part: "Eyes",
    Cost: 0,
    Attack: "-",
    Shield: 25,
    Heal: "-",
    CardEffect: " Innate. Draw 2 cards. Banish.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Peace Maker",
    Part: "Ear",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Apply Weak for 2 turns. If target previously has Weak, deal 15 more DMG.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Peace Maker",
    Part: "Mouth",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Apply Weak for 2 turns. If target previously has Weak, deal 15 more DMG.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Pigeon Post",
    Part: "Back",
    Cost: 1,
    Attack: 55,
    Shield: "-",
    Heal: "-",
    CardEffect: " Add 1 Blackmail to Opponent's hand.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Pink Cheek",
    Part: "Ear",
    Cost: 0,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect: " Discard up to 2 cards then draw that many. Banish.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Post Fight",
    Part: "Tail",
    Cost: 1,
    Attack: 100,
    Shield: "-",
    Heal: "-",
    CardEffect: " This Axie loses 35 HP.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Raven",
    Part: "Back",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " Shuffle 1 Jinx into your opponent's discard pile.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Risky Bird",
    Part: "Ear",
    Cost: 1,
    Attack: 90,
    Shield: "-",
    Heal: "-",
    CardEffect: " Apply Weak to this Axie for 2 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Robin",
    Part: "Eyes",
    Cost: 1,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect: " Summon a Little Robin.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Rubber Duckling",
    Part: "Back",
    Cost: 0,
    Attack: "-",
    Shield: "-",
    Heal: 5,
    CardEffect:
      " Retain. Heal any Ally. Gain 1 Energy. If retained, +15 Heal Bonus (up to +45). Banish.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Swallow",
    Part: "Tail",
    Cost: 1,
    Attack: 70,
    Shield: "-",
    Heal: "-",
    CardEffect: " If Initial, deal 15 more DMG.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "The Last One",
    Part: "Tail",
    Cost: 1,
    Attack: 70,
    Shield: "-",
    Heal: "-",
    CardEffect: " Deal 20 more DMG if this is the only card in your hand.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Tri Feather",
    Part: "Back",
    Cost: 1,
    Attack: 25,
    Shield: "-",
    Heal: "-",
    CardEffect: " Attack all enemies.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Trump",
    Part: "Horn",
    Cost: 1,
    Attack: 65,
    Shield: "-",
    Heal: "-",
    CardEffect: " Deal 20 more DMG for each Trump card used this turn.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Wing Horn",
    Part: "Horn",
    Cost: 1,
    Attack: 65,
    Shield: "-",
    Heal: "-",
    CardEffect: " If Initial, this attack targets the second frontmost enemy.",
    Class: "Beast",
    Tag: "Attack",
  },
];
let Bug = [
  {
    Name: "Ant",
    Part: "Tail",
    Cost: 1,
    Attack: "-",
    Shield: 40,
    Heal: "-",
    CardEffect: " Apply Taunt to this Axie for 4 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Antenna",
    Part: "Horn",
    Cost: 1,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect: " Scry 4 cards. Banish.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Beetle Spike",
    Part: "Ear",
    Cost: 1,
    Attack: 45,
    Shield: "-",
    Heal: "-",
    CardEffect: " Deal pure DMG. Apply Bleed for 4 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Bookworm",
    Part: "Eyes",
    Cost: 0,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect: " Put 1 Bug card from your draw pile into your hand. Banish",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Brimstone",
    Part: "Ears",
    Cost: 1,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Retain. Next turn, draw 3 random 0 Energy cards from your deck into your hand.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Buzz Buzz",
    Part: "Back",
    Cost: 1,
    Attack: 20,
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Attack all enemies. Shuffle 1 Daze into your opponent's discard pile.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Caterpillars",
    Part: "Horn",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " Apply Fear for 4 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Centipede",
    Part: "Tail",
    Cost: 0,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Apply 3 Poison. Add a copy of this card to your discard pile when used.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Cute Bunny",
    Part: "Mouth",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " Apply Fear for 4 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Ear Breathing",
    Part: "Ear",
    Cost: 2,
    Attack: 30,
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Randomly Deal 4 hits. Shuffle 1 Goo per enemy hit into opponent's discard pile.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Earwing",
    Part: "Ear",
    Cost: 1,
    Attack: 20,
    Shield: "-",
    Heal: "-",
    CardEffect: " Attack all enemies. Deal 3 bonus DMG per card on your hand.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Fish Snack",
    Part: "Tail",
    Cost: 1,
    Attack: "-",
    Shield: 60,
    Heal: "-",
    CardEffect:
      " Target any ally. Next turn, after the target is attacked. apply Weak to the Attacker for 4 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Garish Worm",
    Part: "Back",
    Cost: 2,
    Attack: 120,
    Shield: "-",
    Heal: "-",
    CardEffect: " Apply 2 Poison per Attack card played this turn.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Gravel Ant",
    Part: "Tail",
    Cost: 1,
    Attack: "-",
    Shield: 60,
    Heal: "-",
    CardEffect:
      " Target any ally. Next turn, after the target is attacked, apply Fear to the Attacker for 4 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Kotaro",
    Part: "Eyes",
    Cost: 1,
    Attack: 50,
    Shield: "-",
    Heal: "-",
    CardEffect: " Attack 1 random enemy and apply Death Mark for 4 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Ladybug Googles",
    Part: "Eyes",
    Cost: 2,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect: " Each turn, if any Enemy has Shield, draw 2 additional cards.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Lagging",
    Part: "Horn",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " Apply Weak for 4 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Larva",
    Part: "Ear",
    Cost: 0,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Scry 2 cards. Gain 1 Energy if discard 1 skill card upon scrying.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Leaf Bug",
    Part: "Horn",
    Cost: 1,
    Attack: "-",
    Shield: 45,
    Heal: "-",
    CardEffect: " Whenever this is drawn, gain 30 Shield.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Leaf Bug",
    Part: "Ear",
    Cost: 1,
    Attack: "-",
    Shield: 45,
    Heal: "-",
    CardEffect: " Whenever this is drawn, gain 30 Shield.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Leaf Bug",
    Part: "Tail",
    Cost: 1,
    Attack: "-",
    Shield: "-",
    Heal: 45,
    CardEffect: " Whenever this is drawn, gain 30 Shield.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Mosquito",
    Part: "Mouth",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " Heal HP equal to 50% of unblocked DMG.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Neo",
    Part: "Eyes",
    Cost: 1,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Look at the top 4 cards of your opponent's draw pile. Banish.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Nerdy",
    Part: "Eyes",
    Cost: 0,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect: " Discard up to 2 cards then draw that many. Banish.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Parasite",
    Part: "Horn",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " Look at the top 2 cards of your opponent's draw pile.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Pincer",
    Part: "Mouth",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " Apply Bleed for 4 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Pliers",
    Part: "Horn",
    Cost: 1,
    Attack: 65,
    Shield: "-",
    Heal: "-",
    CardEffect: " Deal 25% more DMG to shield.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Pupae",
    Part: "Tail",
    Cost: 1,
    Attack: "-",
    Shield: 60,
    Heal: "-",
    CardEffect:
      " Target any ally. Next turn, after the target is attacked, it gains 2 Damage Boost.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Sandal",
    Part: "Back",
    Cost: 2,
    Attack: 100,
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Apply Fear for 2 turns. If target previously has Fear, deal 50% more DMG.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Scarab",
    Part: "Back",
    Cost: 1,
    Attack: 30,
    Shield: "-",
    Heal: "-",
    CardEffect: " Gain 30 Shield. Apply Doubt for 4 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Shield Crusher",
    Part: "Tail",
    Cost: 1,
    Attack: 65,
    Shield: "-",
    Heal: "-",
    CardEffect: " Deal 25% more DMG to shield.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Snail Shell",
    Part: "Back",
    Cost: 1,
    Attack: "-",
    Shield: 60,
    Heal: "-",
    CardEffect:
      " Target any ally. Next turn, after the target is attacked, shuffle 1 Goo into your opponent's discard pile.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Spiky Wing",
    Part: "Back",
    Cost: 1,
    Attack: 70,
    Shield: "-",
    Heal: "-",
    CardEffect: " Deal 25% more DMG to shield.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Square Teeth",
    Part: "Mouth",
    Cost: 0,
    Attack: 25,
    Shield: "-",
    Heal: "-",
    CardEffect: " If Initial, deal bonus DMG equal to current Shield.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Tassels",
    Part: "Ear",
    Cost: 1,
    Attack: "-",
    Shield: "-",
    Heal: 10,
    CardEffect: " Heal your team. Heal for 4 bonus HP per Card on your hand.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Termite",
    Part: "Ears",
    Cost: 0,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Innate. Remove 30% of all Enemies' Shield. Applies Fragile for 4 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Thorny Caterpillar",
    Part: "Tail",
    Cost: 2,
    Attack: 110,
    Shield: "-",
    Heal: "-",
    CardEffect: " Deal 50% more DMG against debuffed enemy.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Twin Tail",
    Part: "Tail",
    Cost: 1,
    Attack: 35,
    Shield: "-",
    Heal: "-",
    CardEffect: " Deal 2 hits.",
    Class: "Beast",
    Tag: "Attack",
  },
];
let Plant = [
  {
    Name: "Bambooo Shoot",
    Part: "Horn",
    Cost: 1,
    Attack: 65,
    Shield: "-",
    Heal: "-",
    CardEffect: " Deal 20 more DMG for each Bamboo card used this turn.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Beech",
    Part: "Horn",
    Cost: 2,
    Attack: 90,
    Shield: "-",
    Heal: "-",
    CardEffect: " Gain 75 shield.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Beetroot",
    Part: "Mouth",
    Cost: 1,
    Attack: 50,
    Shield: "-",
    Heal: "-",
    CardEffect: " Draw 1 Card.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Bidens",
    Part: "Back",
    Cost: 1,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect: " Target any ally. Remove all debuffs on target.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Blossom",
    Part: "Eyes",
    Cost: 0,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect: " Put 1 Plant card from your draw pile into your hand. Banish.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Cactus",
    Part: "Horn",
    Cost: 1,
    Attack: 65,
    Shield: "-",
    Heal: "-",
    CardEffect: " If Initial, deal 15 more DMG.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Carrot",
    Part: "Tail",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " Gain 1 Energy if this Attack causes HP loss to target.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Cattail",
    Part: "Tail",
    Cost: 1,
    Attack: 50,
    Shield: "-",
    Heal: "-",
    CardEffect: " Apply Taunt to this Axie for 4 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Clover",
    Part: "Ear",
    Cost: 1,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect: " Summon 1 Clover.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Confusion",
    Part: "Eyes",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " Shuffle 1 Confused into your opponent's discard pile.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Cucumber Slice",
    Part: "Eyes",
    Cost: 2,
    Attack: "-",
    Shield: "-",
    Heal: 50,
    CardEffect: " Heal your team and apply 5 Healing Boost.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Death Shroom",
    Part: "Back",
    Cost: 1,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect: " Apply 3 Poison x 4 times to random Enemies.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Forest Hero",
    Part: "Back",
    Cost: 2,
    Attack: 140,
    Shield: "-",
    Heal: "-",
    CardEffect: "-",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Hatsune",
    Part: "Tail",
    Cost: 1,
    Attack: "-",
    Shield: 60,
    Heal: "-",
    CardEffect:
      " Target any ally. Next turn, after the target is attacked, apply Fear to the Attacker for 4 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Herbivore",
    Part: "Mouth",
    Cost: 1,
    Attack: 65,
    Shield: "-",
    Heal: "-",
    CardEffect: " If Initial, heal 15 HP.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Hollow",
    Part: "Ear",
    Cost: 0,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect: " This Axie loses 75 HP. Summon a Trunk.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Hot Butt",
    Part: "Tail",
    Cost: 1,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect: " Shuffle 3 Burns into your opponent's discard pile.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Leafy",
    Part: "Ear",
    Cost: 0,
    Attack: 10,
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Randomly deal 2 hits. Consume up to 3 Leafs to deal 5 DMG per Leaf consumed.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Lotus",
    Part: "Ear",
    Cost: 1,
    Attack: "-",
    Shield: 50,
    Heal: 30,
    CardEffect: "-",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Mandarine",
    Part: "Horn",
    Cost: 1,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect: " Innate. Add 2 Mandarines to your hand.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Mint",
    Part: "Back",
    Cost: 1,
    Attack: "-",
    Shield: 20,
    Heal: "-",
    CardEffect: " Shield your team and apply 1 Cleanser.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Mystery Seed",
    Part: "Tail",
    Cost: 1,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Retain. Pick a Card. Next turn, add 2 copies of it to your hand. Banish.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Papi",
    Part: "Eyes",
    Cost: 1,
    Attack: "-",
    Shield: "-",
    Heal: 45,
    CardEffect: " Target any ally. Whenever this is drawn, heal 20 HP.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Persimmon",
    Part: "Horn",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " Target any Enemy.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Potato Leaf",
    Part: "Tail",
    Cost: 1,
    Attack: 70,
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Card Effect: Gain Stealth if there is at least 1 living Ally.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Pumpkin",
    Part: "Back",
    Cost: 1,
    Attack: "-",
    Shield: 60,
    Heal: "-",
    CardEffect:
      " Target any ally. Next turn, after the target is attacked, draw 1 card.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Rosa",
    Part: "Ear",
    Cost: 0,
    Attack: 5,
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Innate. Apply 2 Poison and Slep for 2 turns to a random enemy. Banish.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Rose Bud",
    Part: "Horn",
    Cost: 1,
    Attack: "-",
    Shield: "-",
    Heal: 70,
    CardEffect: "-",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Sakura",
    Part: "Ear",
    Cost: 2,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Target any ally. Whenever you play a card this battle, heal this Axie 10 HP.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Serious",
    Part: "Mouth",
    Cost: 1,
    Attack: 90,
    Shield: "-",
    Heal: "-",
    CardEffect: " Discard 1 card from your hand.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Shield Shroom",
    Part: "Tail",
    Cost: 1,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Retain. Add 30 shield and restore 30 HP to this Axie and all its Minions.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Shitake",
    Part: "Back",
    Cost: 1,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect: " Summon a Mushroom.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Silence Whisper",
    Part: "Mouth",
    Cost: 1,
    Attack: "-",
    Shield: 65,
    Heal: "-",
    CardEffect: " Target any ally.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Sprout",
    Part: "Tail",
    Cost: 1,
    Attack: "-",
    Shield: 40,
    Heal: 40,
    CardEffect: " Target any ally.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Strawberry Shortcake",
    Part: "Horn",
    Cost: 2,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect: " Add 2 Strawberry to your hand.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Suculent",
    Part: "Back",
    Cost: 0,
    Attack: "-",
    Shield: 50,
    Heal: "-",
    CardEffect: " Banish.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Tropical Guardian",
    Part: "Tail",
    Cost: 1,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Retain. Add 30 shield and restore 30 HP to this Axie and all its Minions.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Turnip",
    Part: "Back",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " After your opponent summons a unit, deal 25 DMG to it.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Watering Can",
    Part: "Back",
    Cost: 1,
    Attack: "-",
    Shield: 60,
    Heal: "-",
    CardEffect:
      " Target any ally. Next turn, after an ally is attacked, add 1 Pure Water to your hand.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Watermelon",
    Part: "Horn",
    Cost: 1,
    Attack: 70,
    Shield: "-",
    Heal: "-",
    CardEffect: " Whenever this is drawn, heal 20 HP.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Yam",
    Part: "Tail",
    Cost: 0,
    Attack: 5,
    Shield: "-",
    Heal: "-",
    CardEffect: " Attack and apply 2 Poison to all enemies.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Zigzag",
    Part: "Mouth",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " Heal HP equal to 50% of unblocked DMG.",
    Class: "Beast",
    Tag: "Attack",
  },
];
let Reptile = [
  {
    Name: "Bone Sail",
    Part: "Back",
    Cost: 1,
    Attack: "-",
    Shield: 60,
    Heal: "-",
    CardEffect:
      " Target any ally. Next turn, after the target is attacked, draw 1 card.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Bumpy",
    Part: "Horn",
    Cost: 2,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Innate. Whenever you play a card this battle, this Axie gains 10 Shield.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Cerastes",
    Part: "Horn",
    Cost: 1,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Target any ally. Next attack against the target is reflected for 85 DMG.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Chemical Fang",
    Part: "Mouth",
    Cost: 1,
    Attack: 50,
    Shield: "-",
    Heal: "-",
    CardEffect: " Deal 2 bonus DMG per Poison stack on target.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Croc",
    Part: "Back",
    Cost: 1,
    Attack: "-",
    Shield: 60,
    Heal: "-",
    CardEffect:
      " Target any ally. Next turn, after the target is attacked. apply Bleed to the attacker for 4 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Curved Spine",
    Part: "Ear",
    Cost: 1,
    Attack: "-",
    Shield: 60,
    Heal: "-",
    CardEffect:
      " Target any ally. Next turn, after the target is attacked, apply Bleed to the attacker for 4 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Friezard",
    Part: "Ear",
    Cost: 1,
    Attack: "-",
    Shield: "-",
    Heal: 20,
    CardEffect:
      " Randomly apply effect 4 times to your team. Heal and apply 1 Damage Boost each time.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Gecko",
    Part: "Eyes",
    Cost: 0,
    Attack: "-",
    Shield: "-",
    Heal: 25,
    CardEffect:
      " This Axie loses 50 HP. Heal and Cleanse 1 debuff on other allies.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Gila",
    Part: "Tail",
    Cost: 2,
    Attack: 40,
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Attack all enemies. Deal 2 bonus DMG per Poison stack on Enemy.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Grass Snake",
    Part: "Tail",
    Cost: 1,
    Attack: 70,
    Shield: "-",
    Heal: "-",
    CardEffect: " Apply Hex for 4 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Green Thorns",
    Part: "Back",
    Cost: 1,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Apply 2 Poison x6 to random targets. Heal this Axie for 20 HP.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Hidden Ears",
    Part: "Ears",
    Cost: 1,
    Attack: "-",
    Shield: 70,
    Heal: "-",
    CardEffect: " Innate.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Iguana",
    Part: "Tail",
    Cost: 1,
    Attack: 70,
    Shield: "-",
    Heal: "-",
    CardEffect: " Apply Weak for 4 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Incisor",
    Part: "Horn",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " Apply Bleed for 4 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Indian Star",
    Part: "Back",
    Cost: 1,
    Attack: "-",
    Shield: 60,
    Heal: "-",
    CardEffect:
      " Target any ally. Next turn, after the target is attacked, reflect 25% of Shield lost.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Kotaro",
    Part: "Mouth",
    Cost: 1,
    Attack: 30,
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Deal 2 hits to random Enemies. Gain 1 Energy if hit at least 2 Enemies.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Pogona",
    Part: "Ear",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " Apply Fragile for 4 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Poison Tube",
    Part: "Horn",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Apply 3 Poison. Add a copy of this card to your discard pile when used.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Punky",
    Part: "Eyes",
    Cost: 2,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect: " Apply 2 Poison to all Enemies at the start of your turn.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Razor Bite",
    Part: "Mouth",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " Heal HP equal to 50% of unblocked DMG.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Red Ear",
    Part: "Back",
    Cost: 1,
    Attack: "-",
    Shield: 65,
    Heal: "-",
    CardEffect: " Target any ally.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Scaly Spear",
    Part: "Horn",
    Cost: 1,
    Attack: 65,
    Shield: "-",
    Heal: "-",
    CardEffect: " Deal 20 more DMG for each Spear card used this turn.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Scaly Spoon",
    Part: "Horn",
    Cost: 1,
    Attack: "-",
    Shield: 60,
    Heal: "-",
    CardEffect:
      " Target any ally. Next turn, after the target is attacked, reflect 25% of Shield lost.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Scar",
    Part: "Eyes",
    Cost: 0,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Take 1 Reptile card from your draw pile and add it to your hand. Banish.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Scarab",
    Part: "Eyes",
    Cost: 0,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Put 1 Reptile card from your draw pile into your hand. Banish.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Sidebarb",
    Part: "Ear",
    Cost: 1,
    Attack: 50,
    Shield: "-",
    Heal: "-",
    CardEffect: " Apply 2 Poison and Bleed for 4 turns to a random Enemy.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Small Frill",
    Part: "Ear",
    Cost: 1,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect: " Aplpy 3 Poison to all Enemies. Heal this Axie for 30 HP.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Snake Jar",
    Part: "Tail",
    Cost: 1,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Target any ally. Negate the next HP loss against the target, up to 90 HP.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Swirl",
    Part: "Ear",
    Cost: 1,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect: " Shuffle 3 Confused into your opponent's discard pile.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Tiny Dino",
    Part: "Tail",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Retain. This card gains 15 bonus DMG per turn if Retained. Max: 4 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Tiny Turtle",
    Part: "Mouth",
    Cost: 1,
    Attack: 50,
    Shield: "-",
    Heal: "-",
    CardEffect:
      " Apply Stunned for 2 turns if this attack causes HP loss to target.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Toothless Bite",
    Part: "Mouth",
    Cost: 1,
    Attack: 65,
    Shield: "-",
    Heal: "-",
    CardEffect: " If Initial, this attack targets the furthest enemy.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Topaz",
    Part: "Eyes",
    Cost: 1,
    Attack: 25,
    Shield: "-",
    Heal: "-",
    CardEffect: " Deal 10 bonus DMG per your banished card.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Tri Spikes",
    Part: "Back",
    Cost: 1,
    Attack: 25,
    Shield: "-",
    Heal: "-",
    CardEffect: " Deal 3 hits.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Tricky",
    Part: "Eyes",
    Cost: 1,
    Attack: "-",
    Shield: "-",
    Heal: 50,
    CardEffect:
      " If Initial, swap this card with 1 selected Card in your Banish Pile.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Unko",
    Part: "Horn",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " Shuffle 1 Goo into your opponent's discard pile.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Venom Nail",
    Part: "Ears",
    Cost: 2,
    Attack: "-",
    Shield: "-",
    Heal: "-",
    CardEffect: " Retain. Double Target's Poison stacks.",
    Class: "Beast",
    Tag: "Attack",
  },
  {
    Name: "Wall Gecko",
    Part: "Tail",
    Cost: 1,
    Attack: 60,
    Shield: "-",
    Heal: "-",
    CardEffect: " This Axie loses 50 HP. Take 30% less DMG for 4 turns.",
    Class: "Beast",
    Tag: "Attack",
  },
];
//all
let in_cards = [...Aquatic, ...Beast, ...Bird, ...Bug, ...Plant, ...Reptile];
