let Plant = [
  {
    name: "Bambooo Shoot",
    part: "Horn",
    cost: 1,
    attack: 65,
    shield: "-",
    heal: "-",
    cardEffect: " Deal 20 more DMG for each Bamboo card used this turn.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Beech",
    part: "Horn",
    cost: 2,
    attack: 90,
    shield: "-",
    heal: "-",
    cardEffect: " Gain 75 shield.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Beetroot",
    part: "Mouth",
    cost: 1,
    attack: 50,
    shield: "-",
    heal: "-",
    cardEffect: " Draw 1 Card.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Bidens",
    part: "Back",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect: " Target any ally. Remove all debuffs on target.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Blossom",
    part: "Eyes",
    cost: 0,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect: " Put 1 Plant card from your draw pile into your hand. Banish.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Cactus",
    part: "Horn",
    cost: 1,
    attack: 65,
    shield: "-",
    heal: "-",
    cardEffect: " If Initial, deal 15 more DMG.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Carrot",
    part: "Tail",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Gain 1 Energy if this attack causes HP loss to target.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Cattail",
    part: "Tail",
    cost: 1,
    attack: 50,
    shield: "-",
    heal: "-",
    cardEffect: " Apply Taunt to this Axie for 4 turns.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Clover",
    part: "Ear",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect: " Summon 1 Clover.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Confusion",
    part: "Eyes",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Shuffle 1 Confused into your opponent's discard pile.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Cucumber Slice",
    part: "Eyes",
    cost: 2,
    attack: "-",
    shield: "-",
    heal: 50,
    cardEffect: " heal your team and apply 5 healing Boost.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Death Shroom",
    part: "Back",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect: " Apply 3 Poison x 4 times to random Enemies.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Forest Hero",
    part: "Back",
    cost: 2,
    attack: 140,
    shield: "-",
    heal: "-",
    cardEffect: "-",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Hatsune",
    part: "Tail",
    cost: 1,
    attack: "-",
    shield: 60,
    heal: "-",
    cardEffect:
      " Target any ally. Next turn, after the target is attacked, apply Fear to the attacker for 4 turns.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Herbivore",
    part: "Mouth",
    cost: 1,
    attack: 65,
    shield: "-",
    heal: "-",
    cardEffect: " If Initial, heal 15 HP.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Hollow",
    part: "Ear",
    cost: 0,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect: " This Axie loses 75 HP. Summon a Trunk.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Hot Butt",
    part: "Tail",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect: " Shuffle 3 Burns into your opponent's discard pile.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Leafy",
    part: "Ear",
    cost: 0,
    attack: 10,
    shield: "-",
    heal: "-",
    cardEffect:
      " Randomly deal 2 hits. Consume up to 3 Leafs to deal 5 DMG per Leaf consumed.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Lotus",
    part: "Ear",
    cost: 1,
    attack: "-",
    shield: 50,
    heal: 30,
    cardEffect: "-",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Mandarine",
    part: "Horn",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect: " Innate. Add 2 Mandarines to your hand.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Mint",
    part: "Back",
    cost: 1,
    attack: "-",
    shield: 20,
    heal: "-",
    cardEffect: " shield your team and apply 1 Cleanser.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Mystery Seed",
    part: "Tail",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect:
      " Retain. Pick a Card. Next turn, add 2 copies of it to your hand. Banish.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Papi",
    part: "Eyes",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: 45,
    cardEffect: " Target any ally. Whenever this is drawn, heal 20 HP.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Persimmon",
    part: "Horn",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Target any Enemy.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Potato Leaf",
    part: "Tail",
    cost: 1,
    attack: 70,
    shield: "-",
    heal: "-",
    cardEffect:
      " Card Effect: Gain Stealth if there is at least 1 living Ally.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Pumpkin",
    part: "Back",
    cost: 1,
    attack: "-",
    shield: 60,
    heal: "-",
    cardEffect:
      " Target any ally. Next turn, after the target is attacked, draw 1 card.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Rosa",
    part: "Ear",
    cost: 0,
    attack: 5,
    shield: "-",
    heal: "-",
    cardEffect:
      " Innate. Apply 2 Poison and Slep for 2 turns to a random enemy. Banish.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Rose Bud",
    part: "Horn",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: 70,
    cardEffect: "-",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Sakura",
    part: "Ear",
    cost: 2,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect:
      " Target any ally. Whenever you play a card this battle, heal this Axie 10 HP.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Serious",
    part: "Mouth",
    cost: 1,
    attack: 90,
    shield: "-",
    heal: "-",
    cardEffect: " Discard 1 card from your hand.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "shield Shroom",
    part: "Tail",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect:
      " Retain. Add 30 shield and restore 30 HP to this Axie and all its Minions.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Shitake",
    part: "Back",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect: " Summon a Mushroom.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Silence Whisper",
    part: "Mouth",
    cost: 1,
    attack: "-",
    shield: 65,
    heal: "-",
    cardEffect: " Target any ally.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Sprout",
    part: "Tail",
    cost: 1,
    attack: "-",
    shield: 40,
    heal: 40,
    cardEffect: " Target any ally.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Strawberry Shortcake",
    part: "Horn",
    cost: 2,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect: " Add 2 Strawberry to your hand.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Suculent",
    part: "Back",
    cost: 0,
    attack: "-",
    shield: 50,
    heal: "-",
    cardEffect: " Banish.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Tropical Guardian",
    part: "Tail",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect:
      " Retain. Add 30 shield and restore 30 HP to this Axie and all its Minions.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Turnip",
    part: "Back",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " After your opponent summons a unit, deal 25 DMG to it.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Watering Can",
    part: "Back",
    cost: 1,
    attack: "-",
    shield: 60,
    heal: "-",
    cardEffect:
      " Target any ally. Next turn, after an ally is attacked, add 1 Pure Water to your hand.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Watermelon",
    part: "Horn",
    cost: 1,
    attack: 70,
    shield: "-",
    heal: "-",
    cardEffect: " Whenever this is drawn, heal 20 HP.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Yam",
    part: "Tail",
    cost: 0,
    attack: 5,
    shield: "-",
    heal: "-",
    cardEffect: " attack and apply 2 Poison to all enemies.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Zigzag",
    part: "Mouth",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " heal HP equal to 50% of unblocked DMG.",
    class: "Plant",
    tag: "",
    img: "",
    keyword: "-",
  },
];
