let Reptile = [
  {
    name: "Bone Sail",
    part: "Back",
    cost: 1,
    attack: "-",
    shield: 60,
    heal: "-",
    cardEffect:
      " Target any ally. Next turn, after the target is attacked, draw 1 card.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Bumpy",
    part: "Horn",
    cost: 2,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect:
      " Innate. Whenever you play a card this battle, this Axie gains 10 shield.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Cerastes",
    part: "Horn",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect:
      " Target any ally. Next attack against the target is reflected for 85 DMG.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Chemical Fang",
    part: "Mouth",
    cost: 1,
    attack: 50,
    shield: "-",
    heal: "-",
    cardEffect: " Deal 2 bonus DMG per Poison stack on target.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Croc",
    part: "Back",
    cost: 1,
    attack: "-",
    shield: 60,
    heal: "-",
    cardEffect:
      " Target any ally. Next turn, after the target is attacked. apply Bleed to the attacker for 4 turns.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Curved Spine",
    part: "Ear",
    cost: 1,
    attack: "-",
    shield: 60,
    heal: "-",
    cardEffect:
      " Target any ally. Next turn, after the target is attacked, apply Bleed to the attacker for 4 turns.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Friezard",
    part: "Ear",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: 20,
    cardEffect:
      " Randomly apply effect 4 times to your team. heal and apply 1 Damage Boost each time.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Gecko",
    part: "Eyes",
    cost: 0,
    attack: "-",
    shield: "-",
    heal: 25,
    cardEffect:
      " This Axie loses 50 HP. heal and Cleanse 1 debuff on other allies.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Gila",
    part: "Tail",
    cost: 2,
    attack: 40,
    shield: "-",
    heal: "-",
    cardEffect:
      " attack all enemies. Deal 2 bonus DMG per Poison stack on Enemy.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Grass Snake",
    part: "Tail",
    cost: 1,
    attack: 70,
    shield: "-",
    heal: "-",
    cardEffect: " Apply Hex for 4 turns.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Green Thorns",
    part: "Back",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect:
      " Apply 2 Poison x6 to random targets. heal this Axie for 20 HP.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Hidden Ears",
    part: "Ears",
    cost: 1,
    attack: "-",
    shield: 70,
    heal: "-",
    cardEffect: " Innate.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Iguana",
    part: "Tail",
    cost: 1,
    attack: 70,
    shield: "-",
    heal: "-",
    cardEffect: " Apply Weak for 4 turns.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Incisor",
    part: "Horn",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Apply Bleed for 4 turns.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Indian Star",
    part: "Back",
    cost: 1,
    attack: "-",
    shield: 60,
    heal: "-",
    cardEffect:
      " Target any ally. Next turn, after the target is attacked, reflect 25% of shield lost.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Kotaro",
    part: "Mouth",
    cost: 1,
    attack: 30,
    shield: "-",
    heal: "-",
    cardEffect:
      " Deal 2 hits to random Enemies. Gain 1 Energy if hit at least 2 Enemies.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Pogona",
    part: "Ear",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Apply Fragile for 4 turns.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Poison Tube",
    part: "Horn",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect:
      " Apply 3 Poison. Add a copy of this card to your discard pile when used.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Punky",
    part: "Eyes",
    cost: 2,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect: " Apply 2 Poison to all Enemies at the start of your turn.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Razor Bite",
    part: "Mouth",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " heal HP equal to 50% of unblocked DMG.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Red Ear",
    part: "Back",
    cost: 1,
    attack: "-",
    shield: 65,
    heal: "-",
    cardEffect: " Target any ally.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Scaly Spear",
    part: "Horn",
    cost: 1,
    attack: 65,
    shield: "-",
    heal: "-",
    cardEffect: " Deal 20 more DMG for each Spear card used this turn.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Scaly Spoon",
    part: "Horn",
    cost: 1,
    attack: "-",
    shield: 60,
    heal: "-",
    cardEffect:
      " Target any ally. Next turn, after the target is attacked, reflect 25% of shield lost.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Scar",
    part: "Eyes",
    cost: 0,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect:
      " Take 1 Reptile card from your draw pile and add it to your hand. Banish.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Scarab",
    part: "Eyes",
    cost: 0,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect:
      " Put 1 Reptile card from your draw pile into your hand. Banish.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Sidebarb",
    part: "Ear",
    cost: 1,
    attack: 50,
    shield: "-",
    heal: "-",
    cardEffect: " Apply 2 Poison and Bleed for 4 turns to a random Enemy.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Small Frill",
    part: "Ear",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect: " Aplpy 3 Poison to all Enemies. heal this Axie for 30 HP.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Snake Jar",
    part: "Tail",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect:
      " Target any ally. Negate the next HP loss against the target, up to 90 HP.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Swirl",
    part: "Ear",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect: " Shuffle 3 Confused into your opponent's discard pile.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Tiny Dino",
    part: "Tail",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect:
      " Retain. This card gains 15 bonus DMG per turn if Retained. Max: 4 turns.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Tiny Turtle",
    part: "Mouth",
    cost: 1,
    attack: 50,
    shield: "-",
    heal: "-",
    cardEffect:
      " Apply Stunned for 2 turns if this attack causes HP loss to target.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Toothless Bite",
    part: "Mouth",
    cost: 1,
    attack: 65,
    shield: "-",
    heal: "-",
    cardEffect: " If Initial, this attack targets the furthest enemy.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Topaz",
    part: "Eyes",
    cost: 1,
    attack: 25,
    shield: "-",
    heal: "-",
    cardEffect: " Deal 10 bonus DMG per your banished card.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Tri Spikes",
    part: "Back",
    cost: 1,
    attack: 25,
    shield: "-",
    heal: "-",
    cardEffect: " Deal 3 hits.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Tricky",
    part: "Eyes",
    cost: 1,
    attack: "-",
    shield: "-",
    heal: 50,
    cardEffect:
      " If Initial, swap this card with 1 selected Card in your Banish Pile.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Unko",
    part: "Horn",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " Shuffle 1 Goo into your opponent's discard pile.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Venom Nail",
    part: "Ears",
    cost: 2,
    attack: "-",
    shield: "-",
    heal: "-",
    cardEffect: " Retain. Double Target's Poison stacks.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
  {
    name: "Wall Gecko",
    part: "Tail",
    cost: 1,
    attack: 60,
    shield: "-",
    heal: "-",
    cardEffect: " This Axie loses 50 HP. Take 30% less DMG for 4 turns.",
    class: "Reptile",
    tag: "",
    img: "",
    keyword: "-",
  },
];
