//要先貼上 [obj]

//將tag[] 轉成 string 壓縮成要的obj
function getFil(arr) {
  let fil = arr.map((el, i, arr) => {
    tagStr = String(el.tags);
    let b = {
      class: el.class,
      name: el.name,
      tag: tagStr,
    };
    return b;
  });
  return fil;
}
//尋找class種族
function getClass(className, arr) {
  let fil = arr.map((el, i, arr) => {
    let nObj = {
      name: el.name,
      tag: el.tag,
    };
    if (el.class === className) {
      return nObj;
    }else{
        return ''
    }
  });
  fil = fil.filter(el => el);
  return fil;
}
//目標
const cards = [
  {
    id: 1,
    class: "aquatic",
    name: "Anemone",
    part: "back",
    text: "Whenever this Axie draws Anenome, restore 20 HP.",
    tags: ["attack"],
    keywords: [""],
    damage: 50,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "aquatic-back-10",
  },
  {
    id: 2,
    class: "aquatic",
    name: "Anemone",
    part: "horn",
    text: "Whenever this Axie draws Anemone restore 20 HP.",
    tags: ["attack"],
    keywords: [""],
    damage: 50,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "aquatic-horn-08",
  },
  {
    id: 3,
    class: "aquatic",
    name: "Baby",
    part: "eyes",
    text: "Attacks deal 33 bonus DMG if HP is above 66%",
    tags: ["power"],
    keywords: [""],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "2",
    img: "aquatic-eyes-01",
  },
  {
    id: 4,
    class: "aquatic",
    name: "Babylonia",
    part: "horn",
    text: "Apply Weak for 4 turns.",
    tags: ["attack"],
    keywords: ["weak"],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "aquatic-horn-02",
  },
  {
    id: 5,
    class: "aquatic",
    name: "Blue Moon",
    part: "back",
    text: "Draw 1 card.",
    tags: ["attack"],
    keywords: [""],
    damage: 50,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "aquatic-back-04",
  },
  {
    id: 6,
    class: "aquatic",
    name: "Bubblemaker",
    part: "ears",
    text: "Target any ally. This ally gains 2 Bubble.",
    tags: ["skill"],
    keywords: ["bubble"],
    damage: 0,
    shield: 70,
    heal: 0,
    cost: "1",
    img: "aquatic-ears-06",
  },
  {
    id: 7,
    class: "aquatic",
    name: "Catfish",
    part: "mouth",
    text: "Restore HP equal to 50% of unblocked DMG.",
    tags: ["attack"],
    keywords: [""],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "aquatic-mouth-04",
  },
  {
    id: 8,
    class: "aquatic",
    name: "Clamshell",
    part: "horn",
    text: "Gain 4 Damage Boost if this attack causes HP loss to target.",
    tags: ["attack"],
    keywords: ["damage boost"],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "aquatic-horn-06",
  },
  {
    id: 9,
    class: "aquatic",
    name: "Clear",
    part: "eyes",
    text: "Discard up to 2 cards then draw that many. Banish.",
    tags: ["skill", "banish"],
    keywords: ["banish"],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "0",
    img: "aquatic-eyes-04",
  },
  {
    id: 10,
    class: "aquatic",
    name: "Gero",
    part: "eyes",
    text: "Apply Fragile for 4 turns.",
    tags: ["attack"],
    keywords: ["fragile"],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "aquatic-eyes-08",
  },
  {
    id: 11,
    class: "aquatic",
    name: "Gill",
    part: "ears",
    text: "Your team gains 1 Bubble.",
    tags: ["attack"],
    keywords: ["bubble"],
    damage: 50,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "aquatic-ears-10",
  },
  {
    id: 12,
    class: "aquatic",
    name: "Goldfish",
    part: "back",
    text: "If Initial, draw 1 card.",
    tags: ["attack"],
    keywords: ["initial"],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "aquatic-back-06",
  },
  {
    id: 13,
    class: "aquatic",
    name: "Hermit",
    part: "back",
    text: "Target any ally. Negate the next attack on this ally.",
    tags: ["secret"],
    keywords: [""],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "aquatic-back-02",
  },
  {
    id: 14,
    class: "aquatic",
    name: "Inkling",
    part: "ears",
    text: "Shuffle 1 Jinx into your opponent's discard pile.",
    tags: ["attack"],
    keywords: ["jinx"],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "aquatic-ears-08",
  },
  {
    id: 15,
    class: "aquatic",
    name: "Koi",
    part: "tail",
    text: "Deal 15 bonus DMG per Aquatic Ally.",
    tags: ["attack"],
    keywords: [""],
    damage: 120,
    shield: 0,
    heal: 0,
    cost: "2",
    img: "aquatic-tail-02",
  },
  {
    id: 16,
    class: "aquatic",
    name: "Lam",
    part: "mouth",
    text: "Deal 20 bonus DMG if this Axie's HP is above 75%.",
    tags: ["attack"],
    keywords: [""],
    damage: 65,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "aquatic-mouth-02",
  },
  {
    id: 17,
    class: "aquatic",
    name: "Navaga",
    part: "tail",
    text: "If Initial, deal 15 more DMG.",
    tags: ["attack"],
    keywords: ["initial"],
    damage: 65,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "aquatic-tail-10",
  },
  {
    id: 18,
    class: "aquatic",
    name: "Nimo",
    part: "ears",
    text: "Gain 1 Energy if this Axie's HP is full.",
    tags: ["skill"],
    keywords: [""],
    damage: 0,
    shield: 0,
    heal: 25,
    cost: "0",
    img: "aquatic-ears-02",
  },
  {
    id: 19,
    class: "aquatic",
    name: "Nimo",
    part: "tail",
    text: "Gain 1 Energy. Banish.",
    tags: ["skill", "banish"],
    keywords: ["banish"],
    damage: 0,
    shield: 0,
    heal: 15,
    cost: "0",
    img: "aquatic-tail-04",
  },
  {
    id: 20,
    class: "aquatic",
    name: "Oranda",
    part: "horn",
    text: "Dispel up to 2 buffs on target.",
    tags: ["attack"],
    keywords: ["dispel"],
    damage: 120,
    shield: 0,
    heal: 0,
    cost: "2",
    img: "aquatic-horn-10",
  },
  {
    id: 21,
    class: "aquatic",
    name: "Perch",
    part: "back",
    text: "Deal 4 hits. Prioritize target with lowest HP.",
    tags: ["attack"],
    keywords: [""],
    damage: 30,
    shield: 0,
    heal: 0,
    cost: "2",
    img: "aquatic-back-12",
  },
  {
    id: 22,
    class: "aquatic",
    name: "Piranha",
    part: "mouth",
    text: "Apply Bleed for 4 turns.",
    tags: ["attack"],
    keywords: ["bleed"],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "aquatic-mouth-10",
  },
  {
    id: 23,
    class: "aquatic",
    name: "Ranchu",
    part: "tail",
    text: "Attack all enemies. Apply Weak for 2 turns.",
    tags: ["attack"],
    keywords: ["weak"],
    damage: 40,
    shield: 0,
    heal: 0,
    cost: "2",
    img: "aquatic-tail-08",
  },
  {
    id: 24,
    class: "aquatic",
    name: "Risky Fish",
    part: "mouth",
    text: "Apply Weak to self for 2 turns.",
    tags: ["attack"],
    keywords: ["weak"],
    damage: 90,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "aquatic-mouth-08",
  },
  {
    id: 24,
    class: "aquatic",
    name: "Seaslug",
    part: "ears",
    text: "Cleanse 2 debuffs. Gain 2 Cleanser.",
    tags: ["attack"],
    keywords: ["cleanse", "cleanser"],
    damage: 110,
    shield: 0,
    heal: 0,
    cost: "2",
    img: "aquatic-ears-12",
  },
  {
    id: 25,
    class: "aquatic",
    name: "Shoal Star",
    part: "horn",
    text: "If the target has no more than 120 HP, kill it instantly.",
    tags: ["attack"],
    keywords: [""],
    damage: 50,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "aquatic-horn-12",
  },
  {
    id: 26,
    class: "aquatic",
    name: "Shrimp",
    part: "tail",
    text: "If Initial, this attack targets the furthest enemy.",
    tags: ["attack"],
    keywords: ["initial"],
    damage: 65,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "aquatic-tail-12",
  },
  {
    id: 27,
    class: "aquatic",
    name: "Sleepless",
    part: "eyes",
    text: "Shuffle 1 Daze into your opponent's discard pile.",
    tags: ["attack"],
    keywords: ["daze"],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "aquatic-eyes-02",
  },
  {
    id: 28,
    class: "aquatic",
    name: "Sponge",
    part: "back",
    text: "Target any ally. Next turn, apply 5 Damage Boost to this ally if its shield is broken.",
    tags: ["secret"],
    keywords: ["damage boost"],
    damage: 0,
    shield: 70,
    heal: 0,
    cost: "1",
    img: "aquatic-back-08",
  },
  {
    id: 29,
    class: "aquatic",
    name: "Tadpole",
    part: "tail",
    text: "Shuffle 1 Jinx into your opponent's discard pile.",
    tags: ["attack"],
    keywords: ["jinx"],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "aquatic-tail-06",
  },
  {
    id: 30,
    class: "aquatic",
    name: "Teal Shell",
    part: "horn",
    text: "Targeted Ally gains 20 shield for each card played before it this turn.",
    tags: ["skill"],
    keywords: [""],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "aquatic-horn-04",
  },
  {
    id: 31,
    class: "aquatic",
    name: "Telescope",
    part: "eyes",
    text: "Take 1 Aquatic card from your draw pile and add it to your hand. Banish.",
    tags: ["skill", "banish"],
    keywords: ["banish"],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "0",
    img: "aquatic-eyes-10",
  },
  {
    id: 32,
    class: "aquatic",
    name: "Tiny Fan",
    part: "ears",
    text: "Draw 1 card. Gain 3 Damage Boost.",
    tags: ["skill"],
    keywords: ["damage boost"],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "0",
    img: "aquatic-ears-04",
  },
  {
    id: 33,
    class: "beast",
    name: "Arco",
    part: "horn",
    text: "This does not trigger Secrets.",
    tags: ["attack"],
    keywords: [""],
    damage: 65,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "beast-horn-12",
  },
  {
    id: 34,
    class: "beast",
    name: "Axie Kiss",
    part: "mouth",
    text: "Target any Enemy. Apply Death Mark for 4 turns if this Axie's HP is below 50%.",
    tags: ["attack"],
    keywords: ["death mark"],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "beast-mouth-08",
  },
  {
    id: 35,
    class: "beast",
    name: "Belieber",
    part: "ears",
    text: "Randomly deal 3 hits. Gain Rage stacks per each unique enemy hit.",
    tags: ["attack"],
    keywords: ["rage"],
    damage: 20,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "beast-ears-12",
  },
  {
    id: 36,
    class: "beast",
    name: "Chubby",
    part: "eyes",
    text: "Attack all enemies.",
    tags: ["attack"],
    keywords: [""],
    damage: 50,
    shield: 0,
    heal: 0,
    cost: "2",
    img: "beast-eyes-10",
  },
  {
    id: 37,
    class: "beast",
    name: "Confident",
    part: "mouth",
    text: "Target any ally. Cleanse 1 debuff and grant 2 Rage.",
    tags: ["skill"],
    keywords: ["clense", "rage"],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "0",
    img: "beast-mouth-10",
  },
  {
    id: 38,
    class: "beast",
    name: "Cottontail",
    part: "tail",
    text: "Heal any ally. Gain 1 Energy. Banish",
    tags: ["skill", "banish"],
    keywords: ["banish"],
    damage: 0,
    shield: 0,
    heal: 15,
    cost: "0",
    img: "beast-tail-02",
  },
  {
    id: 39,
    class: "beast",
    name: "Dual Blade",
    part: "horn",
    text: "Apply Fragile for 4 turns.",
    tags: ["attack"],
    keywords: ["fragile"],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "beast-horn-10",
  },
  {
    id: 40,
    class: "beast",
    name: "Furball",
    part: "back",
    text: "Deal 2 hits.",
    tags: ["attack"],
    keywords: [""],
    damage: 40,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "beast-back-12",
  },
  {
    id: 41,
    class: "beast",
    name: "Gerbil",
    part: "tail",
    text: "If Initial, this attack targets the second frontmost enemy.",
    tags: ["attack"],
    keywords: ["initial"],
    damage: 65,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "beast-tail-12",
  },
  {
    id: 42,
    class: "beast",
    name: "Goda",
    part: "mouth",
    text: "Shuffle 1 Void into your opponent's discard pile. Banish.",
    tags: ["attack", "banish"],
    keywords: ["banish"],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "beast-mouth-04",
  },
  {
    id: 43,
    class: "beast",
    name: "Hare",
    part: "tail",
    text: "If Initial, draw 1 card.",
    tags: ["attack"],
    keywords: ["initial"],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "beast-tail-08",
  },
  {
    id: 44,
    class: "beast",
    name: "Hero",
    part: "back",
    text: "Draw 1 card.",
    tags: ["attack"],
    keywords: [""],
    damage: 50,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "beast-back-04",
  },
  {
    id: 45,
    class: "beast",
    name: "Imp",
    part: "horn",
    text: "Cost 0 Energy in Fury Form.",
    tags: ["attack"],
    keywords: ["fury"],
    damage: 70,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "beast-horn-04",
  },
  {
    id: 46,
    class: "beast",
    name: "Innocent Lamb",
    part: "ears",
    text: "Innate. Select one of this Axie's skill cards and add it to your hand. Banish.",
    tags: ["skill", "innate", "banish"],
    keywords: ["innate", "banish"],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "beast-ears-06",
  },
  {
    id: 47,
    class: "beast",
    name: "Jaguar",
    part: "back",
    text: "Apply Bleed for 4 turns.",
    tags: ["attack"],
    keywords: ["bleed"],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "beast-back-06",
  },
  {
    id: 48,
    class: "beast",
    name: "Little Branch",
    part: "horn",
    text: "Gain 1 Rage per living ally (including Summons).",
    tags: ["attack"],
    keywords: ["rage"],
    damage: 130,
    shield: 0,
    heal: 0,
    cost: "2",
    img: "beast-horn-02",
  },
  {
    id: 49,
    class: "beast",
    name: "Little Peas",
    part: "eyes",
    text: "Apply Vulnerable for 4 turns.",
    tags: ["attack"],
    keywords: ["vulnerable"],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "beast-eyes-04",
  },
  {
    id: 50,
    class: "beast",
    name: "Merry",
    part: "horn",
    text: "Target any ally.",
    tags: ["skill"],
    keywords: [""],
    damage: 0,
    shield: 80,
    heal: 0,
    cost: "1",
    img: "beast-horn-06",
  },
  {
    id: 51,
    class: "beast",
    name: "Nut Cracker",
    part: "ears",
    text: "When played, this Axie's Nut Cracker cards gain 6 DMG this battle.",
    tags: ["attack"],
    keywords: [""],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "beast-ears-04",
  },
  {
    id: 52,
    class: "beast",
    name: "Nut Cracker",
    part: "tail",
    text: "When played, this Axie's Nut Cracker cards gain 6 DMG this battle.",
    tags: ["attack"],
    keywords: [""],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "beast-tail-10",
  },
  {
    id: 53,
    class: "beast",
    name: "Nut Cracker",
    part: "mouth",
    text: "When played, this Axie's Nut Cracker cards gain 6 DMG this battle.",
    tags: ["attack"],
    keywords: [""],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "beast-mouth-02",
  },
  {
    id: 54,
    class: "beast",
    name: "Nyan",
    part: "ears",
    text: "Deal 15 bonus DMG against Bleeding targets.",
    tags: ["attack"],
    keywords: [""],
    damage: 65,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "beast-ears-02",
  },
  {
    id: 55,
    class: "beast",
    name: "Pocky",
    part: "horn",
    text: "Attack random enemy. Apply Taunt for 2 turns.",
    tags: ["attack"],
    keywords: ["taunt"],
    damage: 65,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "beast-horn-08",
  },
  {
    id: 56,
    class: "beast",
    name: "Puppy",
    part: "ears",
    text: "Heal your team. If Initial, remove 1 Curse Card from your deck",
    tags: ["skill"],
    keywords: ["initial"],
    damage: 0,
    shield: 0,
    heal: 25,
    cost: "1",
    img: "beast-ears-10",
  },
  {
    id: 57,
    class: "beast",
    name: "Puppy",
    part: "eyes",
    text: "Take 1 Beast card from your discard pile and add it to your hand. Banish.",
    tags: ["skill", "banish"],
    keywords: ["banish"],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "0",
    img: "beast-eyes-08",
  },
  {
    id: 58,
    class: "beast",
    name: "Rice",
    part: "tail",
    text: "Steal 40 HP. Gain 1 Energy if this Axie's HP is full. Banish",
    tags: ["attack", "banish"],
    keywords: ["steal", "banish"],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "beast-tail-04",
  },
  {
    id: 59,
    class: "beast",
    name: "Risky Beast",
    part: "back",
    text: "Apply Weak to self for 2 turns.",
    tags: ["attack"],
    keywords: ["weak"],
    damage: 90,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "beast-back-08",
  },
  {
    id: 60,
    class: "beast",
    name: "Ronin",
    part: "back",
    text: "Deal 50% more DMG per energy spent this turn.",
    tags: ["attack"],
    keywords: [""],
    damage: 40,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "beast-back-02",
  },
  {
    id: 61,
    class: "beast",
    name: "Shiba",
    part: "tail",
    text: "Your team gains 3 Rage if this Axie's HP is below 50%.",
    tags: ["attack"],
    keywords: ["rage"],
    damage: 130,
    shield: 0,
    heal: 0,
    cost: "2",
    img: "beast-tail-06",
  },
  {
    id: 62,
    class: "beast",
    name: "Timber",
    part: "back",
    text: "Target any ally. Next turn, after an ally is attacked, add 1 Lumber Shield to your hand.",
    tags: ["secret"],
    keywords: ["lumber shield"],
    damage: 0,
    shield: 70,
    heal: 0,
    cost: "1",
    img: "beast-back-10",
  },
  {
    id: 63,
    class: "beast",
    name: "Zeal",
    part: "eyes",
    text: "Take 1 Beast card from your draw pile and add it to your hand. Banish.",
    tags: ["skill", "banish"],
    keywords: ["banish"],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "0",
    img: "beast-eyes-02",
  },
  {
    id: 64,
    class: "beast",
    name: "Zen",
    part: "ears",
    text: "If Initial, this Axie Meditates.",
    tags: ["skill"],
    keywords: ["initial", "meditates"],
    damage: 0,
    shield: 0,
    heal: 65,
    cost: "1",
    img: "beast-ears-08",
  },
  {
    id: 65,
    class: "bird",
    name: "Balloon",
    part: "back",
    text: "Apply Fear for 4 turns.",
    tags: ["attack"],
    keywords: ["fear"],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bird-back-02",
  },
  {
    id: 66,
    class: "bird",
    name: "Cloud",
    part: "tail",
    text: "This attack targets the closest non-summoned enemy.",
    tags: ["attack"],
    keywords: [""],
    damage: 70,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bird-tail-08",
  },
  {
    id: 67,
    class: "bird",
    name: "Cuckoo",
    part: "horn",
    text: "Target an ally. Remove Sleep. The target's next attack this turn deals 50 more DMG.",
    tags: ["skill"],
    keywords: ["sleep"],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bird-horn-04",
  },
  {
    id: 68,
    class: "bird",
    name: "Cupid",
    part: "back",
    text: "Apply Bleed for 4 turns.",
    tags: ["attack"],
    keywords: ["bleed"],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bird-back-04",
  },
  {
    id: 69,
    class: "bird",
    name: "Curly",
    part: "ears",
    text: "Deal 25% more DMG to shield.",
    tags: ["attack"],
    keywords: [""],
    damage: 65,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bird-ears-10",
  },
  {
    id: 70,
    class: "bird",
    name: "Doubletalk",
    part: "mouth",
    text: "If Initial, apply Sleep for 4 turns.",
    tags: ["attack"],
    keywords: ["initial", "sleep"],
    damage: 65,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bird-mouth-02",
  },
  {
    id: 71,
    class: "bird",
    name: "Early Bird",
    part: "ears",
    text: "If Initial, draw 1 card.",
    tags: ["attack"],
    keywords: ["initial"],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bird-ears-04",
  },
  {
    id: 72,
    class: "bird",
    name: "Eggshell",
    part: "horn",
    text: "Apply Taunt to this Axie for 2 turns.",
    tags: ["attack"],
    keywords: ["taunt"],
    damage: 75,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bird-horn-02",
  },
  {
    id: 73,
    class: "bird",
    name: "Feather Fan",
    part: "tail",
    text: "Randomly deal 4 hits. Your team gain 1 Feather per enemy hit.",
    tags: ["attack"],
    keywords: ["feather"],
    damage: 35,
    shield: 0,
    heal: 0,
    cost: "2",
    img: "bird-tail-04",
  },
  {
    id: 74,
    class: "bird",
    name: "Feather Spear",
    part: "horn",
    text: "Deal 20 bonus DMG for each Spear card used this turn.",
    tags: ["attack"],
    keywords: [""],
    damage: 65,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bird-horn-12",
  },
  {
    id: 75,
    class: "bird",
    name: "Granma's Fan",
    part: "tail",
    text: "Innate. Attack all enemies. Apply Vulnerable for 4 turns.",
    tags: ["attack", "innate"],
    keywords: ["innate", "vulnerable"],
    damage: 15,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bird-tail-10",
  },
  {
    id: 76,
    class: "bird",
    name: "Hungry Bird",
    part: "mouth",
    text: "If Initial, heal 15 HP.",
    tags: ["attack"],
    keywords: ["initial"],
    damage: 65,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bird-mouth-08",
  },
  {
    id: 77,
    class: "bird",
    name: "Kestrel",
    part: "horn",
    text: "Apply Disarmed for 2 turns.",
    tags: ["attack"],
    keywords: ["disarmed"],
    damage: 50,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bird-horn-08",
  },
  {
    id: 78,
    class: "bird",
    name: "Kingfisher",
    part: "back",
    text: "Target any ally. The next attack against this ally is reflected for 85 DMG.",
    tags: ["secret"],
    keywords: [""],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bird-back-10",
  },
  {
    id: 79,
    class: "bird",
    name: "Little Owl",
    part: "ears",
    text: "When played, this Axie's Little Owl cards gain +6 DMG this battle.",
    tags: ["attack"],
    keywords: [""],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bird-ears-06",
  },
  {
    id: 80,
    class: "bird",
    name: "Little Owl",
    part: "eyes",
    text: "When played, this Axie's Little Owl cards gain +6 DMG this battle.",
    tags: ["attack"],
    keywords: [""],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bird-eyes-08",
  },
  {
    id: 81,
    class: "bird",
    name: "Little Owl",
    part: "mouth",
    text: "When played, this Axie's Little Owl cards gain +6 DMG this battle.",
    tags: ["attack"],
    keywords: [""],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bird-mouth-10",
  },
  {
    id: 82,
    class: "bird",
    name: "Lucas",
    part: "eyes",
    text: "Take 1 Bird card from your draw pile and add it to your hand. Banish.",
    tags: ["attack", "banish"],
    keywords: ["banish"],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "0",
    img: "bird-eyes-04",
  },
  {
    id: 83,
    class: "bird",
    name: "Mavis",
    part: "eyes",
    text: "Summon 1 Mavis.",
    tags: ["skill"],
    keywords: ["mavis"],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bird-eyes-02",
  },
  {
    id: 84,
    class: "bird",
    name: "Peace Maker",
    part: "ears",
    text: "Apply Weak for 2 turns.If target already has Weak, deal 15 more DMG.",
    tags: ["attack"],
    keywords: ["weak", "weak"],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bird-ears-08",
  },
  {
    id: 85,
    class: "bird",
    name: "Peace Maker",
    part: "mouth",
    text: "Apply Weak for 2 turns.If target already has Weak, deal 15 more DMG.",
    tags: ["attack"],
    keywords: ["weak", "weak"],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bird-mouth-04",
  },
  {
    id: 86,
    class: "bird",
    name: "Pigeon Post",
    part: "back",
    text: "Add 1 Blackmail to Opponent's hand.",
    tags: ["attack"],
    keywords: ["blackmail"],
    damage: 55,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bird-back-08",
  },
  {
    id: 87,
    class: "bird",
    name: "Pink Cheek",
    part: "ears",
    text: "Discard up to 2 cards then draw that many. Banish.",
    tags: ["skill", "banish"],
    keywords: ["banish"],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "0",
    img: "bird-ears-02",
  },
  {
    id: 88,
    class: "bird",
    name: "Post Fight",
    part: "tail",
    text: "This Axie loses 35 HP.",
    tags: ["attack"],
    keywords: [""],
    damage: 100,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bird-tail-12",
  },
  {
    id: 89,
    class: "bird",
    name: "Raven",
    part: "back",
    text: "Shuffle 1 Jinx into your opponent's discard pile.",
    tags: ["attack"],
    keywords: ["jinx"],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bird-back-06",
  },
  {
    id: 90,
    class: "bird",
    name: "Risky Bird",
    part: "ears",
    text: "Apply Weak to this Axie for 2 turns.",
    tags: ["attack"],
    keywords: ["weak"],
    damage: 90,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bird-ears-12",
  },
  {
    id: 91,
    class: "bird",
    name: "Robin",
    part: "eyes",
    text: "Summon a Little Robin.",
    tags: ["skill"],
    keywords: ["little robin"],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bird-eyes-10",
  },
  {
    id: 92,
    class: "bird",
    name: "Swallow",
    part: "tail",
    text: "If Initial, deal 15 more DMG.",
    tags: ["attack"],
    keywords: ["initial"],
    damage: 65,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bird-tail-02",
  },
  {
    id: 93,
    class: "bird",
    name: "The Last One",
    part: "tail",
    text: "Deal 20 more DMG if this is the only card in your hand.",
    tags: ["attack"],
    keywords: [""],
    damage: 70,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bird-tail-06",
  },
  {
    id: 94,
    class: "bird",
    name: "Tri Feather",
    part: "back",
    text: "Attack all enemies.",
    tags: ["attack"],
    keywords: [""],
    damage: 25,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bird-back-12",
  },
  {
    id: 95,
    class: "bird",
    name: "Trump",
    part: "horn",
    text: "Deal 20 more DMG for each Trump card used this turn.",
    tags: ["attack"],
    keywords: [""],
    damage: 65,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bird-horn-06",
  },
  {
    id: 96,
    class: "bird",
    name: "Wing Horn",
    part: "horn",
    text: "If Initial, this attack targets the second- closest enemy.",
    tags: ["attack"],
    keywords: ["initial"],
    damage: 65,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bird-horn-10",
  },
  {
    id: 97,
    class: "aquatic",
    name: "Little Crab",
    part: "ears",
    text: "Ethereal",
    tags: ["attack"],
    keywords: ["ethereal"],
    damage: 80,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "aquatic-ears-01",
  },
  {
    id: 98,
    class: "aquatic",
    name: "Puff",
    part: "tail",
    text: "Retain. Randomly deal X hits",
    tags: ["attack", "retain"],
    keywords: ["retain"],
    damage: 66,
    shield: 0,
    heal: 0,
    cost: "x",
    img: "aquatic-tail-01",
  },
  {
    id: 99,
    class: "beast",
    name: "Buba Brush",
    part: "tail",
    text: "Gain 2 Rage",
    tags: ["attack"],
    keywords: ["rage"],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "beast-tail-03",
  },
  {
    id: 100,
    class: "beast",
    name: "Cub",
    part: "mouth",
    text: "If Initial, draw 1 Skill/Secret Card.",
    tags: ["attack"],
    keywords: ["initial"],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "beast-mouth-05",
  },
  {
    id: 101,
    class: "beast",
    name: "Foxy",
    part: "ears",
    text: "Target the furthest enemy",
    tags: ["attack"],
    keywords: [""],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "beast-ears-03",
  },
  {
    id: 102,
    class: "beast",
    name: "Foxy",
    part: "mouth",
    text: "Retain. Gain 1 Rage. If Retained, +1 Rage when played (cap:3 rounds)",
    tags: ["attack", "retain"],
    keywords: ["retain", "rage"],
    damage: 65,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "beast-mouth-01",
  },
  {
    id: 103,
    class: "beast",
    name: "Puff",
    part: "mouth",
    text: "Heal HP equal to 50% of unblocked DMG",
    tags: ["attack"],
    keywords: [""],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "beast-mouth-03",
  },
  {
    id: 104,
    class: "beast",
    name: "Sparky",
    part: "eyes",
    text: "Gain 4 Rage",
    tags: ["skill"],
    keywords: ["rage"],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "beast-eyes-03",
  },
  {
    id: 105,
    class: "bug",
    name: "Ant",
    part: "tail",
    text: "Apply Taunt to this Axie for 4 turns.",
    tags: ["skill"],
    keywords: ["taunt"],
    damage: 0,
    shield: 70,
    heal: 0,
    cost: "1",
    img: "bug-tail-02",
  },
  {
    id: 106,
    class: "bug",
    name: "Antenna",
    part: "horn",
    text: "Scry 4 cards. Banish.",
    tags: ["skill", "banish"],
    keywords: ["scry", "banish"],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bug-horn-04",
  },
  {
    id: 107,
    class: "bug",
    name: "Beetle Spike",
    part: "ears",
    text: "Deal pure DMG. Apply Bleed for 4 turns.",
    tags: ["attack"],
    keywords: ["bleed"],
    damage: 45,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bug-ears-04",
  },
  {
    id: 108,
    class: "bug",
    name: "Bookworm",
    part: "eyes",
    text: "Take 1 Bug card from your draw pile and add it to your hand. Banish.",
    tags: ["skill", "banish"],
    keywords: ["banish"],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "0",
    img: "bug-eyes-02",
  },
  {
    id: 109,
    class: "bug",
    name: "Buzz Buzz",
    part: "back",
    text: "Attack all enemies. Shuffle 1 Daze into your opponent's discard pile.",
    tags: ["attack"],
    keywords: ["daze"],
    damage: 20,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bug-back-06",
  },
  {
    id: 110,
    class: "bug",
    name: "Caterpillars",
    part: "horn",
    text: "Apply Fear for 4 turns.",
    tags: ["attack"],
    keywords: ["fear"],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bug-horn-06",
  },
  {
    id: 111,
    class: "bug",
    name: "Cute Bunny",
    part: "mouth",
    text: "Apply Fear for 4 turns.",
    tags: ["attack"],
    keywords: ["fear"],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bug-mouth-08",
  },
  {
    id: 112,
    class: "bug",
    name: "Ear Breathing",
    part: "ears",
    text: "Randomly deal 4 hits. Shuffle 1 Goo per enemy hit into opponent's discard pile.",
    tags: ["attack"],
    keywords: ["goo"],
    damage: 30,
    shield: 0,
    heal: 0,
    cost: "2",
    img: "bug-ears-06",
  },
  {
    id: 113,
    class: "bug",
    name: "Earwing",
    part: "ears",
    text: "Attack all enemies. Deal 3 bonus DMG per Card in your hand.",
    tags: ["attack"],
    keywords: [""],
    damage: 20,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bug-ears-12",
  },
  {
    id: 114,
    class: "bug",
    name: "Fish Snack",
    part: "tail",
    text: "Target any ally. Next turn, if targeted ally is attacked, apply Weak to the attacker for 4 turns.",
    tags: ["secret"],
    keywords: ["weak"],
    damage: 0,
    shield: 70,
    heal: 0,
    cost: "1",
    img: "bug-tail-06",
  },
  {
    id: 115,
    class: "bug",
    name: "Garish Worm",
    part: "back",
    text: "Apply 2 Poison per Attack Card played this turn.",
    tags: ["attack"],
    keywords: ["poison"],
    damage: 120,
    shield: 0,
    heal: 0,
    cost: "2",
    img: "bug-back-04",
  },
  {
    id: 116,
    class: "bug",
    name: "Gravel Ant",
    part: "tail",
    text: "Target any ally. Next turn, if targeted ally is attacked, apply Fear to the attacker for 4 turns.",
    tags: ["secret"],
    keywords: ["fear"],
    damage: 0,
    shield: 70,
    heal: 0,
    cost: "1",
    img: "bug-tail-08",
  },
  {
    id: 117,
    class: "bug",
    name: "Kotaro",
    part: "eyes",
    text: "Attack 1 random enemy and apply Death Mark for 4 turns.",
    tags: ["attack"],
    keywords: ["death mark"],
    damage: 50,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bug-eyes-10",
  },
  {
    id: 118,
    class: "bug",
    name: "Lagging",
    part: "horn",
    text: "Apply Weak for 4 turns.",
    tags: ["attack"],
    keywords: ["weak"],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bug-horn-02",
  },
  {
    id: 119,
    class: "bug",
    name: "Larva",
    part: "ears",
    text: "Scry 2 cards.Gain 1 Energy if you discard a skill card upon scrying.",
    tags: ["skill"],
    keywords: ["scry"],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "0",
    img: "bug-ears-02",
  },
  {
    id: 120,
    class: "bug",
    name: "Leaf bug",
    part: "horn",
    text: "Whenever this is drawn, gain 30 Shield.",
    tags: ["skill"],
    keywords: [""],
    damage: 0,
    shield: 55,
    heal: 0,
    cost: "1",
    img: "bug-horn-12",
  },
  {
    id: 121,
    class: "bug",
    name: "Leaf bug",
    part: "ears",
    text: "Whenever this is drawn, gain 30 Shield.",
    tags: ["skill"],
    keywords: [""],
    damage: 0,
    shield: 55,
    heal: 0,
    cost: "1",
    img: "bug-ears-08",
  },
  {
    id: 122,
    class: "bug",
    name: "Mosquito",
    part: "mouth",
    text: "Restore HP equal to 50% of unblocked DMG.",
    tags: ["attack"],
    keywords: [""],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bug-mouth-02",
  },
  {
    id: 123,
    class: "bug",
    name: "Neo",
    part: "eyes",
    text: "Look at the top 4 cards of your opponent's draw pile. Banish.",
    tags: ["skill", "banish"],
    keywords: ["banish"],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bug-eyes-04",
  },
  {
    id: 124,
    class: "bug",
    name: "Nerdy",
    part: "eyes",
    text: "Discard up to 2 cards then draw that many. Banish.",
    tags: ["skill", "banish"],
    keywords: ["banish"],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "0",
    img: "bug-eyes-08",
  },
  {
    id: 125,
    class: "bug",
    name: "Parasite",
    part: "horn",
    text: "Look at the top 2 cards of your opponent's draw pile.",
    tags: ["attack"],
    keywords: [""],
    damage: 70,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bug-horn-10",
  },
  {
    id: 126,
    class: "bug",
    name: "Pincer",
    part: "mouth",
    text: "Apply Bleed for 4 turns.",
    tags: ["attack"],
    keywords: ["bleed"],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bug-mouth-04",
  },
  {
    id: 127,
    class: "bug",
    name: "Pliers",
    part: "horn",
    text: "Deal 25% more DMG to shield.",
    tags: ["attack"],
    keywords: [""],
    damage: 65,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bug-horn-08",
  },
  {
    id: 128,
    class: "bug",
    name: "Pupae",
    part: "tail",
    text: "Target any ally. Next turn, if targeted ally is attacked, it gains 2 Damage Boost.",
    tags: ["secret"],
    keywords: ["damage boost"],
    damage: 0,
    shield: 70,
    heal: 0,
    cost: "1",
    img: "bug-tail-10",
  },
  {
    id: 129,
    class: "bug",
    name: "Sandal",
    part: "back",
    text: "Apply Fear for 2 turns.If target already has Fear, deal 50% more DMG.",
    tags: ["attack"],
    keywords: ["fear", "fear"],
    damage: 100,
    shield: 0,
    heal: 0,
    cost: "2",
    img: "bug-back-08",
  },
  {
    id: 130,
    class: "bug",
    name: "Scarab",
    part: "back",
    text: "Gain 40 Shield. Apply Doubt for 4 turns.",
    tags: ["attack"],
    keywords: ["doubt"],
    damage: 30,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bug-back-10",
  },
  {
    id: 131,
    class: "bug",
    name: "Snail Shell",
    part: "back",
    text: "Target any ally. Next turn, after the target is attacked, shuffle 1 Goo into your opponent's discard pile.",
    tags: ["secret"],
    keywords: ["goo"],
    damage: 0,
    shield: 70,
    heal: 0,
    cost: "1",
    img: "bug-back-02",
  },
  {
    id: 132,
    class: "bug",
    name: "Spiky Wing",
    part: "back",
    text: "Deal 25% more DMG to shield.",
    tags: ["attack"],
    keywords: [""],
    damage: 65,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bug-back-12",
  },
  {
    id: 133,
    class: "bug",
    name: "Square Teeth",
    part: "mouth",
    text: "If Initial, deal bonus DMG equal to current Shield.",
    tags: ["attack"],
    keywords: ["initial"],
    damage: 25,
    shield: 0,
    heal: 0,
    cost: "0",
    img: "bug-mouth-10",
  },
  {
    id: 134,
    class: "bug",
    name: "Tassels",
    part: "ears",
    text: "Heal your team. Restore 4 bonus HP per Card in your hand.",
    tags: ["skill"],
    keywords: [""],
    damage: 0,
    shield: 0,
    heal: 10,
    cost: "1",
    img: "bug-ears-10",
  },
  {
    id: 135,
    class: "bug",
    name: "Thorny Caterpillar",
    part: "tail",
    text: "Deal 50% more DMG against debuffed enemies.",
    tags: ["attack"],
    keywords: [""],
    damage: 100,
    shield: 0,
    heal: 0,
    cost: "2",
    img: "bug-tail-12",
  },
  {
    id: 136,
    class: "bug",
    name: "Twin Tail",
    part: "tail",
    text: "Deal 2 hits",
    tags: ["attack"],
    keywords: [""],
    damage: 40,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "bug-tail-04",
  },
  {
    id: 137,
    class: "plant",
    name: "Bambooo Shoot",
    part: "horn",
    text: "Deal 20 more DMG for each Bamboo card used this turn.",
    tags: ["attack"],
    keywords: [""],
    damage: 65,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "plant-horn-02",
  },
  {
    id: 138,
    class: "plant",
    name: "Beech",
    part: "horn",
    text: "Gain 75 Shield.",
    tags: ["attack"],
    keywords: [""],
    damage: 90,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "plant-horn-04",
  },
  {
    id: 139,
    class: "plant",
    name: "Bidens",
    part: "back",
    text: "Target any Ally. Remove all debuffs on this Ally.",
    tags: ["skill"],
    keywords: [""],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "plant-back-06",
  },
  {
    id: 140,
    class: "plant",
    name: "Blossom",
    part: "eyes",
    text: "Take 1 Plant card from your draw pile and add it to your hand. Banish.",
    tags: ["skill", "banish"],
    keywords: ["banish"],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "0",
    img: "plant-eyes-10",
  },
  {
    id: 141,
    class: "plant",
    name: "Cactus",
    part: "horn",
    text: "If Initial, deal 15 more DMG.",
    tags: ["attack"],
    keywords: [""],
    damage: 65,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "plant-horn-10",
  },
  {
    id: 142,
    class: "plant",
    name: "Carrot",
    part: "tail",
    text: "Gain 1 Energy if this Attack causes HP loss to target.",
    tags: ["attack"],
    keywords: [""],
    damage: 40,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "plant-tail-02",
  },
  {
    id: 143,
    class: "plant",
    name: "Cattail",
    part: "tail",
    text: "Apply Taunt to this Axie for 4 turns.",
    tags: ["attack"],
    keywords: ["taunt"],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "plant-tail-04",
  },
  {
    id: 144,
    class: "plant",
    name: "Clover",
    part: "ears",
    text: "Summon 1 Clover.",
    tags: ["skill"],
    keywords: ["clover"],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "plant-ears-04",
  },
  {
    id: 145,
    class: "plant",
    name: "Confusion",
    part: "eyes",
    text: "Shuffle 1 Confused into your opponent's discard pile.",
    tags: ["attack"],
    keywords: ["confused"],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "plant-eyes-04",
  },
  {
    id: 146,
    class: "plant",
    name: "Cucumber Slice",
    part: "eyes",
    text: "Heal your team and apply 5 Healing Boost.",
    tags: ["skill"],
    keywords: ["healing boost"],
    damage: 0,
    shield: 0,
    heal: 50,
    cost: "2",
    img: "plant-eyes-08",
  },
  {
    id: 147,
    class: "plant",
    name: "Hatsune",
    part: "tail",
    text: "Target any ally. Next turn, if targeted ally is attacked, apply Fear to the attacker for 4 turns",
    tags: ["secret"],
    keywords: ["fear"],
    damage: 0,
    shield: 70,
    heal: 0,
    cost: "1",
    img: "plant-tail-06",
  },
  {
    id: 148,
    class: "plant",
    name: "Herbivore",
    part: "mouth",
    text: "If Initial, restore 15 HP.",
    tags: ["attack"],
    keywords: ["initial"],
    damage: 65,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "plant-mouth-08",
  },
  {
    id: 149,
    class: "plant",
    name: "Hollow",
    part: "ears",
    text: "This Axie loses 75 HP. Summon a Trunk.",
    tags: ["skill"],
    keywords: ["trunk"],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "0",
    img: "plant-ears-10",
  },
  {
    id: 150,
    class: "plant",
    name: "Hot Butt",
    part: "tail",
    text: "Shuffle 3 Burns into your opponent's discard pile.",
    tags: ["skill"],
    keywords: ["burn"],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "plant-tail-12",
  },
  {
    id: 151,
    class: "plant",
    name: "Leafy",
    part: "ears",
    text: "Randomly deal 2 hits. Consume up to 3 Leafs to deal 5 DMG per Leaf consumed.",
    tags: ["attack"],
    keywords: ["leaf", "leaf"],
    damage: 10,
    shield: 0,
    heal: 0,
    cost: "0",
    img: "plant-ears-02",
  },
  {
    id: 152,
    class: "plant",
    name: "Lotus",
    part: "ears",
    text: "",
    tags: ["skill"],
    keywords: [""],
    damage: 0,
    shield: 50,
    heal: 30,
    cost: "1",
    img: "plant-ears-12",
  },
  {
    id: 153,
    class: "plant",
    name: "Mint",
    part: "back",
    text: "Shield your team and apply 1 Cleanser.",
    tags: ["skill"],
    keywords: ["cleanser"],
    damage: 0,
    shield: 30,
    heal: 0,
    cost: "1",
    img: "plant-back-10",
  },
  {
    id: 154,
    class: "plant",
    name: "Papi",
    part: "eyes",
    text: "Target any ally. Whenever this is drawn, restore 20 HP.",
    tags: ["skill"],
    keywords: [""],
    damage: 0,
    shield: 0,
    heal: 45,
    cost: "1",
    img: "plant-eyes-02",
  },
  {
    id: 155,
    class: "plant",
    name: "Potato Leaf",
    part: "tail",
    text: "Gain Stealth if there is at least 1 living ally.",
    tags: ["attack"],
    keywords: ["stealth"],
    damage: 65,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "plant-tail-10",
  },
  {
    id: 156,
    class: "plant",
    name: "Pumpkin",
    part: "back",
    text: "Target any ally. Next turn, after the ally is attacked, draw 1 card.",
    tags: ["secret"],
    keywords: [""],
    damage: 0,
    shield: 70,
    heal: 0,
    cost: "1",
    img: "plant-back-12",
  },
  {
    id: 157,
    class: "plant",
    name: "Rosa",
    part: "ears",
    text: "Innate. Apply 2 Poison and Sleep for 2 turns to a random enemy.Banish.",
    tags: ["attack", "innate", "banish"],
    keywords: ["innate", "poison", "sleep", "banish"],
    damage: 5,
    shield: 0,
    heal: 0,
    cost: "0",
    img: "plant-ears-06",
  },
  {
    id: 158,
    class: "plant",
    name: "Rose Bud",
    part: "horn",
    text: "",
    tags: ["skill"],
    keywords: [""],
    damage: 0,
    shield: 0,
    heal: 70,
    cost: "1",
    img: "plant-horn-06",
  },
  {
    id: 159,
    class: "plant",
    name: "Sakura",
    part: "ears",
    text: "Target any ally. Whenever you play a card this battle, restore 10 HP to this ally.",
    tags: ["power"],
    keywords: [""],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "2",
    img: "plant-ears-08",
  },
  {
    id: 160,
    class: "plant",
    name: "Serious",
    part: "mouth",
    text: "Select 1 card to discard from your hand.",
    tags: ["attack"],
    keywords: [""],
    damage: 90,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "plant-mouth-02",
  },
  {
    id: 161,
    class: "plant",
    name: "Shiitake",
    part: "back",
    text: "Summon a Mushroom.",
    tags: ["skill"],
    keywords: ["mushroom"],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "plant-back-04",
  },
  {
    id: 162,
    class: "plant",
    name: "Silence Whisper",
    part: "mouth",
    text: "Target any ally.",
    tags: ["skill"],
    keywords: [""],
    damage: 0,
    shield: 0,
    heal: 65,
    cost: "1",
    img: "plant-mouth-10",
  },
  {
    id: 163,
    class: "plant",
    name: "Strawberry Shortcake",
    part: "horn",
    text: "Add 2 Strawberry to your hand.",
    tags: ["skill"],
    keywords: ["strawberry"],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "2",
    img: "plant-horn-08",
  },
  {
    id: 164,
    class: "plant",
    name: "Turnip",
    part: "back",
    text: "After your opponent summons a unit, deal 25 DMG to it.",
    tags: ["attack"],
    keywords: [""],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "plant-back-02",
  },
  {
    id: 165,
    class: "plant",
    name: "Watering Can",
    part: "back",
    text: "Target any ally. Next turn, after any ally is attacked, add 1 Pure Water to your hand.",
    tags: ["secret"],
    keywords: ["pure water"],
    damage: 0,
    shield: 70,
    heal: 0,
    cost: "1",
    img: "plant-back-08",
  },
  {
    id: 166,
    class: "plant",
    name: "Watermelon",
    part: "horn",
    text: "Whenever this is drawn, restore 20 HP.",
    tags: ["attack"],
    keywords: [""],
    damage: 50,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "plant-horn-12",
  },
  {
    id: 167,
    class: "plant",
    name: "Yam",
    part: "tail",
    text: "Attack and apply 2 Poison to all enemies.",
    tags: ["attack"],
    keywords: ["poison"],
    damage: 15,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "plant-tail-08",
  },
  {
    id: 168,
    class: "plant",
    name: "Zigzag",
    part: "mouth",
    text: "Restore HP equal to 50% of unblocked DMG.",
    tags: ["attack"],
    keywords: [""],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "plant-mouth-04",
  },
  {
    id: 169,
    class: "plant",
    name: "Beetroot",
    part: "mouth",
    text: "Draw 1 Card",
    tags: ["attack"],
    keywords: [""],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "plant-mouth-01",
  },
  {
    id: 170,
    class: "plant",
    name: "Forest Hero",
    part: "back",
    text: "",
    tags: ["attack"],
    keywords: [""],
    damage: 145,
    shield: 0,
    heal: 0,
    cost: "2",
    img: "plant-back-03",
  },
  {
    id: 171,
    class: "plant",
    name: "Mandarine",
    part: "horn",
    text: "Innate. Add 2 Mandarines to your hand.",
    tags: ["skill"],
    keywords: ["Innate", "mandarine"],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "plant-horn-03",
  },
  {
    id: 172,
    class: "plant",
    name: "Persimmon",
    part: "horn",
    text: "Target any Enemy",
    tags: ["attack"],
    keywords: [""],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "plant-horn-01",
  },
  {
    id: 173,
    class: "plant",
    name: "Risky Trunk",
    part: "eyes",
    text: "Heal all allies",
    tags: ["skill"],
    keywords: [""],
    damage: 0,
    shield: 0,
    heal: 50,
    cost: "2",
    img: "plant-eyes-01",
  },
  {
    id: 174,
    class: "plant",
    name: "Sprout",
    part: "tail",
    text: "Target any ally",
    tags: ["skill"],
    keywords: [""],
    damage: 0,
    shield: 40,
    heal: 40,
    cost: "1",
    img: "plant-tail-01",
  },
  {
    id: 175,
    class: "plant",
    name: "Succulent",
    part: "back",
    text: "Banish.",
    tags: ["skill", "banish"],
    keywords: ["banish"],
    damage: 0,
    shield: 50,
    heal: 0,
    cost: "0",
    img: "plant-back-01",
  },
  {
    id: 176,
    class: "reptile",
    name: "Bone Sail",
    part: "back",
    text: "Target any ally. Next turn, after the target is attacked, draw 1 card.",
    tags: ["secret"],
    keywords: [""],
    damage: 0,
    shield: 70,
    heal: 0,
    cost: "1",
    img: "reptile-back-02",
  },
  {
    id: 177,
    class: "reptile",
    name: "Bumpy",
    part: "horn",
    text: "Innate. Whenever you play a card this battle, this Axie gains 10 Shield.",
    tags: ["power", "innate"],
    keywords: ["innate"],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "2",
    img: "reptile-horn-12",
  },
  {
    id: 178,
    class: "reptile",
    name: "Cerastes",
    part: "horn",
    text: "Target any ally. The Next attack against the target is reflected for 85 DMG.",
    tags: ["secret"],
    keywords: [""],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "reptile-horn-06",
  },
  {
    id: 179,
    class: "reptile",
    name: "Croc",
    part: "back",
    text: "Target any ally. Next turn, after the target is attacked, apply Bleed to the attacker for 4 turns.",
    tags: ["secret"],
    keywords: ["bleed"],
    damage: 0,
    shield: 70,
    heal: 0,
    cost: "1",
    img: "reptile-back-12",
  },
  {
    id: 180,
    class: "reptile",
    name: "Curved Spine",
    part: "ears",
    text: "Target any ally. Next turn, if targeted ally is attacked, apply Bleed to the attacker for 4 turns.",
    tags: ["secret"],
    keywords: ["bleed"],
    damage: 0,
    shield: 70,
    heal: 0,
    cost: "1",
    img: "reptile-ears-06",
  },
  {
    id: 181,
    class: "reptile",
    name: "Friezard",
    part: "ears",
    text: "Randomly apply effect 4 times to your team. Heal and apply 1 Damage Boost each time.",
    tags: ["skill"],
    keywords: ["damage boost"],
    damage: 0,
    shield: 0,
    heal: 20,
    cost: "1",
    img: "reptile-ears-04",
  },
  {
    id: 182,
    class: "reptile",
    name: "Gecko",
    part: "eyes",
    text: "This Axie loses 50 HP. Heal and Cleanse 1 debuff on all other allies.",
    tags: ["skill"],
    keywords: ["cleanse"],
    damage: 0,
    shield: 0,
    heal: 25,
    cost: "0",
    img: "reptile-eyes-02",
  },
  {
    id: 183,
    class: "reptile",
    name: "Gila",
    part: "tail",
    text: "Attack all enemies. Deal 2 bonus DMG per Poison stack on Enemy.",
    tags: ["attack"],
    keywords: ["poison"],
    damage: 40,
    shield: 0,
    heal: 0,
    cost: "2",
    img: "reptile-tail-10",
  },
  {
    id: 184,
    class: "reptile",
    name: "Grass Snake",
    part: "tail",
    text: "Apply Hex for 4 turns",
    tags: ["attack"],
    keywords: ["hex"],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "reptile-tail-12",
  },
  {
    id: 185,
    class: "reptile",
    name: "Green Thorns",
    part: "back",
    text: "Apply 2 Poison x 6 times to random targets. Restore 20 HP to this Axie.",
    tags: ["skill"],
    keywords: [""],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "reptile-back-06",
  },
  {
    id: 186,
    class: "reptile",
    name: "Iguana",
    part: "tail",
    text: "Apply Weak for 4 turns.",
    tags: ["attack"],
    keywords: ["weak"],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "reptile-tail-04",
  },
  {
    id: 187,
    class: "reptile",
    name: "Incisor",
    part: "horn",
    text: "Apply Bleed for 4 turns.",
    tags: ["attack"],
    keywords: ["bleed"],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "reptile-horn-10",
  },
  {
    id: 188,
    class: "reptile",
    name: "Indian Star",
    part: "back",
    text: "Target any ally. Next turn, after the target is attacked, reflect 25% of Shield lost.",
    tags: ["secret"],
    keywords: [""],
    damage: 0,
    shield: 70,
    heal: 0,
    cost: "1",
    img: "reptile-back-08",
  },
  {
    id: 189,
    class: "reptile",
    name: "Kotaro",
    part: "mouth",
    text: "Deal 2 hits to random Enemies. Gain 1 Energy if at least 2 Enemies are hit.",
    tags: ["attack"],
    keywords: [""],
    damage: 30,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "reptile-mouth-04",
  },
  {
    id: 190,
    class: "reptile",
    name: "Pogona",
    part: "ears",
    text: "Apply Fragile for 4 turns.",
    tags: ["attack"],
    keywords: ["fragile"],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "reptile-ears-02",
  },
  {
    id: 191,
    class: "reptile",
    name: "Razor Bite",
    part: "mouth",
    text: "Restore HP equal to 50% of unblocked DMG.",
    tags: ["attack"],
    keywords: [""],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "reptile-mouth-08",
  },
  {
    id: 192,
    class: "reptile",
    name: "Red Ear",
    part: "back",
    text: "Target any ally.",
    tags: ["skill"],
    keywords: [""],
    damage: 0,
    shield: 80,
    heal: 0,
    cost: "1",
    img: "reptile-back-10",
  },
  {
    id: 193,
    class: "reptile",
    name: "Scaly Spear",
    part: "horn",
    text: "Deal 20 bonus DMG for each Spear card used this turn.",
    tags: ["attack"],
    keywords: [""],
    damage: 65,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "reptile-horn-04",
  },
  {
    id: 194,
    class: "reptile",
    name: "Scaly Spoon",
    part: "horn",
    text: "Target any ally. Next turn, after the target is attacked, reflect 25% of Shield lost.",
    tags: ["secret"],
    keywords: [""],
    damage: 0,
    shield: 70,
    heal: 0,
    cost: "1",
    img: "reptile-horn-08",
  },
  {
    id: 195,
    class: "reptile",
    name: "Scar",
    part: "eyes",
    text: "Take 1 Reptile card from your draw pile and add it to your hand. Banish.",
    tags: ["skill", "banish"],
    keywords: ["banish"],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "0",
    img: "reptile-eyes-08",
  },
  {
    id: 196,
    class: "reptile",
    name: "Sidebarb",
    part: "eyes",
    text: "Apply 2 Poison stacks and Bleed for 4 turns to a random Enemy.",
    tags: ["attack"],
    keywords: ["poison", "bleed"],
    damage: 50,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "reptile-ears-12",
  },
  {
    id: 197,
    class: "reptile",
    name: "Small Frill",
    part: "ears",
    text: "Apply 3 Poison to all Enemies.Restore 30 HP to this Axie.",
    tags: ["skill"],
    keywords: ["poison"],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "reptile-ears-08",
  },
  {
    id: 198,
    class: "reptile",
    name: "Snake Jar",
    part: "tail",
    text: "Target any ally. Negate the next HP loss against the target, up to 90 HP.",
    tags: ["secret"],
    keywords: [""],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "reptile-tail-08",
  },
  {
    id: 199,
    class: "reptile",
    name: "Swirl",
    part: "ears",
    text: "Shuffle 3 Confused into your opponent's discard pile.",
    tags: ["skill"],
    keywords: ["confused"],
    damage: 0,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "reptile-ears-10",
  },
  {
    id: 200,
    class: "reptile",
    name: "Tiny Dino",
    part: "tail",
    text: "Retain. This card gains 15 bonus DMG per turn if Retained. Max: 4 turns.",
    tags: ["attack", "retain"],
    keywords: ["retain"],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "reptile-tail-06",
  },
  {
    id: 201,
    class: "reptile",
    name: "Tiny Turtle",
    part: "mouth",
    text: "Target any Enemy. Apply Stunned for 2 turns if this attack causes HP loss to target.",
    tags: ["attack"],
    keywords: ["stunned"],
    damage: 50,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "reptile-mouth-10",
  },
  {
    id: 202,
    class: "reptile",
    name: "Toothless Bite",
    part: "mouth",
    text: "If Initial, this attack targets the furthest enemy.",
    tags: ["attack"],
    keywords: ["initial"],
    damage: 65,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "reptile-mouth-02",
  },
  {
    id: 203,
    class: "reptile",
    name: "Topaz",
    part: "eyes",
    text: "Deal 10 bonus DMG for each of your banished cards.",
    tags: ["attack"],
    keywords: [""],
    damage: 25,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "reptile-eyes-10",
  },
  {
    id: 204,
    class: "reptile",
    name: "Tri Spikes",
    part: "back",
    text: "Deal 3 hits.",
    tags: ["attack"],
    keywords: [""],
    damage: 25,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "reptile-back-04",
  },
  {
    id: 205,
    class: "reptile",
    name: "Tricky",
    part: "eyes",
    text: "If Initial, swap this card with 1 Card in your Banish Pile.",
    tags: ["skill"],
    keywords: ["initial"],
    damage: 0,
    shield: 0,
    heal: 50,
    cost: "1",
    img: "reptile-eyes-04",
  },
  {
    id: 206,
    class: "reptile",
    name: "Unko",
    part: "horn",
    text: "Shuffle 1 Goo into your opponent's discard pile.",
    tags: ["attack"],
    keywords: ["goo"],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "reptile-horn-02",
  },
  {
    id: 207,
    class: "reptile",
    name: "Wall Gecko",
    part: "tail",
    text: "This Axie loses 50 HP and takes 30% less DMG for 4 turns.",
    tags: ["attack"],
    keywords: [""],
    damage: 60,
    shield: 0,
    heal: 0,
    cost: "1",
    img: "reptile-tail-02",
  },
  {
    id: 208,
    class: "reptile",
    name: "Hidden Ears",
    part: "ears",
    text: "Innate.",
    tags: ["skill"],
    keywords: ["innate"],
    damage: 0,
    shield: 60,
    heal: 0,
    cost: "1",
    img: "reptile-ears-03",
  },
];

//input
let INPUT = Reptile

let tagger = getClass("reptile", getFil(cards));
// console.log(tagger);

//合併陣列 主,副
function merger(arr1, arr2) {
  for (let i = 0; i < arr1.length; i++) {
    let targetObj = arr2.find((el) => el.name === arr1[i].name);
    if (targetObj) {
      arr1[i].tag = targetObj.tag;
    } else {
      console.log(arr1[i].name);
    }
  }
}

merger(INPUT, tagger);

console.log(INPUT);

// function question(obj, arr) {
//   let keyArr = Object.keys(obj);
//   for (let i = 0; i < arr.length; i++) {
//     let k = arr[i].name;
//     let tag = keyArr.find((k) => object[k] === value);
//     if (tag) {
//       arr[i].tag = tag;
//     } else {
//       console.log(k);
//     }
//   }
// }
